/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See https://github.com/smbp/flux-tts for the source code.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluxTtsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/templates.ts
var import_obsidian = require("obsidian");
var FILENAME_TEMPLATE_KEYS = [
  "year",
  "month",
  "day",
  "hour",
  "minute",
  "second",
  "date",
  "time",
  "datetime"
];
var NOTE_TEMPLATE_KEYS = [
  ...FILENAME_TEMPLATE_KEYS,
  "transcript",
  "audioPath",
  "audioEmbed",
  "originalTranscript"
];
function createTemplateContext(date) {
  const pad = (value) => String(value).padStart(2, "0");
  const year = String(date.getFullYear());
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hour = pad(date.getHours());
  const minute = pad(date.getMinutes());
  const second = pad(date.getSeconds());
  const dateValue = `${year}-${month}-${day}`;
  const timeValue = `${hour}-${minute}-${second}`;
  return {
    year,
    month,
    day,
    hour,
    minute,
    second,
    date: dateValue,
    time: timeValue,
    datetime: `${dateValue} ${timeValue}`
  };
}
function renderTemplate(template, values) {
  return String(template).replace(/\{\{(.*?)\}\}/g, (_match, key) => {
    var _a;
    const normalizedKey = String(key).trim();
    return (_a = values[normalizedKey]) != null ? _a : "";
  });
}
function validateTemplate(template, allowedKeys) {
  const unknownKeys = [];
  const withoutPlaceholders = String(template).replace(/\{\{(.*?)\}\}/g, (_match, key) => {
    const normalizedKey = String(key).trim();
    if (!allowedKeys.includes(normalizedKey)) {
      unknownKeys.push(normalizedKey);
    }
    return "";
  });
  if (withoutPlaceholders.includes("{") || withoutPlaceholders.includes("}")) {
    return { valid: false, error: "Unbalanced braces \u2014 every placeholder needs matching {{ and }}." };
  }
  if (unknownKeys.length) {
    const listed = unknownKeys.map((key) => `{{${key}}}`).join(", ");
    return { valid: false, error: `Unknown placeholder: ${listed}` };
  }
  return { valid: true };
}
function sanitizeFileName(fileName) {
  const cleaned = String(fileName).replace(/[\\/:*?"<>|#^[\]{}]/g, "-").replace(/\s+/g, " ").trim();
  return cleaned || "Recording";
}
function sanitizeFolderPath(folderPath) {
  return (0, import_obsidian.normalizePath)(
    String(folderPath || "").split("/").map((part) => sanitizeFileName(part)).filter(Boolean).join("/")
  );
}

// src/settings.ts
var GROQ_MODELS = [
  { id: "whisper-large-v3-turbo", name: "Whisper Large v3 Turbo (fast)" },
  { id: "whisper-large-v3", name: "Whisper Large v3 (accurate)" }
];
var DEFAULT_SETTINGS = {
  model: "whisper-large-v3-turbo",
  saveLocation: "audio-folder",
  audioFolder: "audio recordings",
  noteFolderMode: "root",
  noteFolder: "",
  audioNameTemplate: "{{date}} {{time}}",
  noteNameTemplate: "Transcription_{{date}} {{time}}",
  useTemplate: false,
  noteTemplatePath: "",
  startDelayMs: 0,
  cleanupTranscript: false,
  segmentedTranscript: false,
  autoMediaTranscripts: false,
  recordingNoteEnabled: true,
  recordingNoteFolderMode: "root",
  recordingNoteFolder: "",
  recordingNoteBehavior: "reuse"
};
var API_KEY_MASK = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
var FluxTtsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        type: "group",
        heading: "Transcription service",
        items: [
          { name: "Groq API key", render: (setting) => this.renderApiKeySetting(setting) },
          {
            name: "Groq model",
            desc: "Turbo is the default for fastest transcription.",
            control: { type: "dropdown", key: "model", options: Object.fromEntries(GROQ_MODELS.map((model) => [model.id, model.name])) }
          }
        ]
      },
      {
        type: "group",
        heading: "Recording",
        items: [
          {
            name: "Live recording note",
            desc: "Open a temporary Recording... note with a live waveform and Stop button while recording.",
            control: { type: "toggle", key: "recordingNoteEnabled" }
          },
          {
            name: "Recording note location",
            desc: "Choose where Recording....md is stored.",
            visible: () => this.plugin.settings.recordingNoteEnabled,
            control: {
              type: "dropdown",
              key: "recordingNoteFolderMode",
              options: { root: "Vault root", attachments: "Obsidian attachments folder", custom: "Custom folder" }
            }
          },
          {
            name: "Recording note folder",
            desc: "Vault-relative folder used for the temporary recording note.",
            visible: () => this.plugin.settings.recordingNoteEnabled && this.plugin.settings.recordingNoteFolderMode === "custom",
            control: { type: "text", key: "recordingNoteFolder", placeholder: "Recordings" }
          },
          {
            name: "Recording note behavior",
            desc: "Reuse preserves the note. Delete and recreate replaces it when the next recording starts.",
            visible: () => this.plugin.settings.recordingNoteEnabled,
            control: { type: "dropdown", key: "recordingNoteBehavior", options: { reuse: "Reuse existing note", recreate: "Delete and recreate" } }
          },
          {
            name: "Sync warning",
            desc: "Frequent file deletion and creation may cause unnecessary activity or conflicts with fast synchronization tools.",
            visible: () => this.plugin.settings.recordingNoteEnabled && this.plugin.settings.recordingNoteBehavior === "recreate"
          },
          {
            name: "Recording start delay",
            desc: "Milliseconds to wait after the microphone opens before capture begins.",
            control: { type: "slider", key: "startDelayMs", min: 0, max: 2e3, step: 100 }
          }
        ]
      },
      {
        type: "group",
        heading: "Audio files",
        items: [
          {
            name: "Audio save location",
            desc: "Choose where recorded audio files are written.",
            control: { type: "dropdown", key: "saveLocation", options: { "audio-folder": "Separate audio folder", attachments: "Obsidian attachments folder", root: "Vault root" } }
          },
          {
            name: "Audio folder",
            desc: "Used when save location is set to a separate audio folder.",
            visible: () => this.plugin.settings.saveLocation === "audio-folder",
            control: { type: "text", key: "audioFolder" }
          },
          { name: "Audio filename", render: (setting) => this.renderTemplateSetting(setting, this.audioTemplateOptions()) }
        ]
      },
      {
        type: "group",
        heading: "Transcription notes",
        items: [
          {
            name: "Note save location",
            desc: "Choose where transcription notes are created.",
            control: { type: "dropdown", key: "noteFolderMode", options: { root: "Vault root", attachments: "Obsidian attachments folder", custom: "Separate folder" } }
          },
          {
            name: "Note folder",
            desc: "Used when note save location is set to a separate folder.",
            visible: () => this.plugin.settings.noteFolderMode === "custom",
            control: { type: "text", key: "noteFolder", placeholder: "transcriptions" }
          },
          { name: "Transcription note filename", render: (setting) => this.renderTemplateSetting(setting, this.noteTemplateOptions()) },
          {
            name: "Use note template",
            desc: "When off, notes contain only transcript text and the embedded audio link.",
            control: { type: "toggle", key: "useTemplate" }
          },
          {
            name: "Note template file",
            desc: "Vault path to a Markdown template. Supports transcript, audio, and date/time placeholders.",
            visible: () => this.plugin.settings.useTemplate,
            control: { type: "text", key: "noteTemplatePath", placeholder: "Templates/Transcription.md" }
          }
        ]
      },
      {
        type: "group",
        heading: "Transcript processing",
        items: [
          {
            name: "Automatically transcribe pasted media links",
            desc: "Add a citation-style transcript footnote when a supported media link is pasted.",
            control: { type: "toggle", key: "autoMediaTranscripts" }
          },
          {
            name: "Clean up transcript with AI",
            desc: "Fix punctuation, remove filler words, and add paragraph breaks while retaining the original.",
            control: { type: "toggle", key: "cleanupTranscript" }
          },
          {
            name: "Timestamped segments",
            desc: "Write timestamped segments linked to their position in the audio file.",
            control: { type: "toggle", key: "segmentedTranscript" }
          }
        ]
      }
    ];
  }
  getControlValue(key) {
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    const settings = this.plugin.settings;
    if (!(key in settings)) return;
    settings[key] = key === "noteTemplatePath" && typeof value === "string" ? (0, import_obsidian2.normalizePath)(value.trim()) : value;
    await this.plugin.saveSettings();
    if (["recordingNoteEnabled", "recordingNoteFolderMode", "recordingNoteBehavior", "saveLocation", "noteFolderMode", "useTemplate"].includes(key)) {
      this.update();
    }
  }
  renderApiKeySetting(setting) {
    const hasApiKey = Boolean(this.plugin.getApiKey());
    setting.setDesc(hasApiKey ? "A key is saved in Obsidian secret storage." : "Stored in Obsidian secret storage.");
    setting.addText((text) => {
      text.setPlaceholder("gsk_...").setValue(hasApiKey ? API_KEY_MASK : "");
      text.inputEl.type = "password";
      text.inputEl.addEventListener("focus", () => {
        if (text.getValue() === API_KEY_MASK) text.setValue("");
      });
      text.inputEl.addEventListener("blur", () => {
        if (!text.getValue().trim() && this.plugin.getApiKey()) text.setValue(API_KEY_MASK);
      });
      text.onChange((value) => {
        const trimmed = value.trim();
        if (trimmed && trimmed !== API_KEY_MASK) this.plugin.setApiKey(trimmed);
      });
    }).addButton((button) => button.setButtonText("Clear").setDisabled(!hasApiKey).onClick(() => {
      this.plugin.setApiKey("");
      this.update();
    }));
  }
  audioTemplateOptions() {
    return {
      name: "Audio filename",
      desc: "Use date and time placeholders such as {{date}}, {{time}}, {{year}}, and {{second}}.",
      exampleExtension: ".m4a",
      fallback: DEFAULT_SETTINGS.audioNameTemplate,
      getValue: () => this.plugin.settings.audioNameTemplate,
      setValue: (value) => {
        this.plugin.settings.audioNameTemplate = value;
      }
    };
  }
  noteTemplateOptions() {
    return {
      name: "Transcription note filename",
      desc: "Uses the same filename placeholders as audio files.",
      exampleExtension: ".md",
      fallback: DEFAULT_SETTINGS.noteNameTemplate,
      getValue: () => this.plugin.settings.noteNameTemplate,
      setValue: (value) => {
        this.plugin.settings.noteNameTemplate = value;
      }
    };
  }
  renderTemplateSetting(setting, options) {
    setting.setDesc(options.desc);
    const previewEl = setting.descEl.createDiv({ cls: "flux-tts-template-preview" });
    const updatePreview = (template) => {
      var _a;
      const validation = validateTemplate(template, FILENAME_TEMPLATE_KEYS);
      previewEl.setText(validation.valid ? `Preview: ${sanitizeFileName(renderTemplate(template, createTemplateContext(/* @__PURE__ */ new Date())))}${options.exampleExtension}` : (_a = validation.error) != null ? _a : "Invalid template.");
      previewEl.toggleClass("flux-tts-template-invalid", !validation.valid);
      return validation.valid;
    };
    setting.addText((text) => text.setValue(options.getValue()).onChange(async (value) => {
      const template = value || options.fallback;
      if (!updatePreview(template)) return;
      options.setValue(template);
      await this.plugin.saveSettings();
    }));
    updatePreview(options.getValue());
  }
};

// src/recording.ts
var import_obsidian3 = require("obsidian");
var MIME_CANDIDATES = [
  { mime: "audio/mp4", extension: "m4a" },
  { mime: "audio/aac", extension: "aac" },
  { mime: "audio/webm;codecs=opus", extension: "webm" },
  { mime: "audio/webm", extension: "webm" },
  { mime: "audio/ogg;codecs=opus", extension: "ogg" },
  { mime: "audio/ogg", extension: "ogg" }
];
var SILENCE_RMS_THRESHOLD = 0.01;
var SILENCE_WARNING_MS = 5e3;
var SILENCE_AUTO_STOP_MS = 6e4;
var SILENCE_POLL_MS = 250;
var RecorderController = class {
  constructor(handlers) {
    this.handlers = handlers;
    this.state = "idle";
    this.cancelRequested = false;
    this.mediaRecorder = null;
    this.mediaStream = null;
    this.chunks = [];
    this.selectedMime = null;
    this.startedAt = 0;
    this.stoppedAt = null;
    this.pausedAt = null;
    this.totalPausedMs = 0;
    this.audioContext = null;
    this.analyser = null;
    this.silenceInterval = null;
    this.deviceChangeHandler = null;
    this.activeDeviceId = "";
    this.disconnectNotified = false;
    this.manuallyPaused = false;
    this.trackEndedHandler = null;
  }
  get isActive() {
    return this.state !== "idle";
  }
  get isRecording() {
    return this.state === "recording";
  }
  get currentState() {
    return this.state;
  }
  /**
   * The live analyser node for the current recording, or null when not
   * recording (or when AudioContext is unavailable). Shared with silence
   * detection — it reads the same signal, it doesn't open a second capture.
   */
  getAnalyser() {
    return this.analyser;
  }
  async start(startDelayMs) {
    if (this.state !== "idle") {
      return;
    }
    this.state = "starting";
    this.handlers.onStateChange("starting");
    this.cancelRequested = false;
    this.stoppedAt = null;
    this.pausedAt = null;
    this.totalPausedMs = 0;
    this.disconnectNotified = false;
    try {
      this.selectedMime = pickMimeType();
      this.mediaStream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const options = this.selectedMime ? { mimeType: this.selectedMime.mime } : void 0;
      const recorder = new MediaRecorder(this.mediaStream, options);
      this.mediaRecorder = recorder;
      this.chunks = [];
      recorder.ondataavailable = (event) => {
        if (event.data && event.data.size > 0) {
          this.chunks.push(event.data);
        }
      };
      recorder.onstop = () => this.finalize();
      if (startDelayMs > 0) {
        await sleep(startDelayMs);
      }
      if (this.cancelRequested) {
        this.cleanup();
        this.state = "idle";
        return;
      }
      recorder.start();
      this.startedAt = Date.now();
      this.state = "recording";
      this.watchSilence();
      this.watchDeviceChanges();
      this.handlers.onStateChange("recording");
    } catch (error) {
      this.cleanup();
      this.state = "idle";
      this.handlers.onStateChange("error", getErrorText(error));
      this.handlers.onStateChange("idle");
      throw error instanceof Error ? error : new Error(String(error));
    }
  }
  stop() {
    if (this.state === "starting") {
      this.cancelRequested = true;
      return;
    }
    if (!["recording", "paused", "recovering", "error"].includes(this.state) || !this.mediaRecorder || this.mediaRecorder.state === "inactive") {
      return;
    }
    this.stoppedAt = Date.now();
    this.state = "idle";
    this.handlers.onStateChange("idle");
    this.mediaRecorder.stop();
  }
  pause(message = "Transcription paused.") {
    if (this.state !== "recording" || !this.mediaRecorder) return;
    this.manuallyPaused = true;
    this.pausedAt = Date.now();
    if (this.mediaRecorder.state === "recording") {
      this.mediaRecorder.requestData();
      this.mediaRecorder.pause();
    }
    this.state = "paused";
    this.stopSilenceWatch();
    this.handlers.onStateChange("paused", message);
  }
  async resume() {
    var _a, _b;
    if (this.state !== "paused" && this.state !== "error") return;
    this.manuallyPaused = false;
    const track = (_a = this.mediaStream) == null ? void 0 : _a.getAudioTracks()[0];
    if ((track == null ? void 0 : track.readyState) === "live" && ((_b = this.mediaRecorder) == null ? void 0 : _b.state) === "paused") {
      this.finishPauseTiming();
      this.mediaRecorder.resume();
      this.state = "recording";
      this.watchSilence();
      this.handlers.onStateChange("recording", "Transcription resumed.");
      return;
    }
    await this.recoverMicrophone();
  }
  /** Tear everything down without producing a recording (plugin unload). */
  dispose() {
    this.cancelRequested = true;
    if (this.mediaRecorder) {
      this.mediaRecorder.onstop = null;
      if (this.mediaRecorder.state === "recording") {
        try {
          this.mediaRecorder.stop();
        } catch (error) {
          console.error(error);
        }
      }
    }
    this.cleanup();
    this.state = "idle";
    this.handlers.onStateChange("idle");
  }
  finalize() {
    var _a, _b, _c;
    const chunks = this.chunks;
    const selectedMime = this.selectedMime;
    const mimeType = (selectedMime == null ? void 0 : selectedMime.mime) || ((_a = chunks[0]) == null ? void 0 : _a.type) || "audio/webm";
    const extension = (selectedMime == null ? void 0 : selectedMime.extension) || extensionFromMime(mimeType);
    const pausedMs = this.totalPausedMs + (this.pausedAt === null ? 0 : ((_b = this.stoppedAt) != null ? _b : Date.now()) - this.pausedAt);
    const durationSeconds = Math.max(0, (((_c = this.stoppedAt) != null ? _c : Date.now()) - this.startedAt - pausedMs) / 1e3);
    this.cleanup();
    this.state = "idle";
    if (!chunks.length) {
      this.handlers.onError(new Error("No audio was captured."));
      return;
    }
    this.handlers.onFinish({
      blob: new Blob(chunks, { type: mimeType }),
      mimeType,
      extension,
      durationSeconds
    });
  }
  cleanup() {
    var _a;
    this.stopSilenceWatch();
    if (this.deviceChangeHandler && ((_a = navigator.mediaDevices) == null ? void 0 : _a.removeEventListener)) {
      navigator.mediaDevices.removeEventListener("devicechange", this.deviceChangeHandler);
      this.deviceChangeHandler = null;
    }
    if (this.mediaStream) {
      const track = this.mediaStream.getAudioTracks()[0];
      if (track && this.trackEndedHandler) track.removeEventListener("ended", this.trackEndedHandler);
      this.mediaStream.getTracks().forEach((track2) => track2.stop());
      this.mediaStream = null;
    }
    this.trackEndedHandler = null;
    this.mediaRecorder = null;
    this.chunks = [];
    this.selectedMime = null;
  }
  watchSilence() {
    if (typeof AudioContext === "undefined" || !this.mediaStream) {
      return;
    }
    let analyser;
    try {
      this.audioContext = new AudioContext();
      const source = this.audioContext.createMediaStreamSource(this.mediaStream);
      analyser = this.audioContext.createAnalyser();
      analyser.fftSize = 2048;
      source.connect(analyser);
      this.analyser = analyser;
      if (this.audioContext.state === "suspended") {
        void this.audioContext.resume();
      }
    } catch (error) {
      console.error(error);
      return;
    }
    const data = new Uint8Array(analyser.fftSize);
    let hasHeardSound = false;
    let silenceStartedAt = Date.now();
    let earlyWarningShown = false;
    this.silenceInterval = window.setInterval(() => {
      var _a;
      if (((_a = this.audioContext) == null ? void 0 : _a.state) !== "running") {
        return;
      }
      analyser.getByteTimeDomainData(data);
      let sum = 0;
      for (let index = 0; index < data.length; index += 1) {
        const value = (data[index] - 128) / 128;
        sum += value * value;
      }
      const rms = Math.sqrt(sum / data.length);
      if (rms > SILENCE_RMS_THRESHOLD) {
        hasHeardSound = true;
        silenceStartedAt = null;
        return;
      }
      if (silenceStartedAt === null) {
        silenceStartedAt = Date.now();
      }
      const silenceElapsed = Date.now() - silenceStartedAt;
      if (!hasHeardSound && !earlyWarningShown && silenceElapsed >= SILENCE_WARNING_MS) {
        earlyWarningShown = true;
        new import_obsidian3.Notice("No audio detected from your microphone. Check your input device.");
      }
      if (silenceElapsed >= SILENCE_AUTO_STOP_MS) {
        this.stopSilenceWatch();
        new import_obsidian3.Notice("No audio detected for over a minute \u2014 stopping the recording automatically to save battery.");
        this.stop();
      }
    }, SILENCE_POLL_MS);
  }
  stopSilenceWatch() {
    if (this.silenceInterval !== null) {
      window.clearInterval(this.silenceInterval);
      this.silenceInterval = null;
    }
    if (this.audioContext) {
      this.audioContext.close().catch(() => {
      });
      this.audioContext = null;
    }
    this.analyser = null;
  }
  watchDeviceChanges() {
    var _a, _b, _c, _d, _e;
    if (!((_a = navigator.mediaDevices) == null ? void 0 : _a.addEventListener)) {
      return;
    }
    if (this.deviceChangeHandler && ((_b = navigator.mediaDevices) == null ? void 0 : _b.removeEventListener)) {
      navigator.mediaDevices.removeEventListener("devicechange", this.deviceChangeHandler);
    }
    const track = (_c = this.mediaStream) == null ? void 0 : _c.getAudioTracks()[0];
    this.activeDeviceId = (_e = (_d = track == null ? void 0 : track.getSettings) == null ? void 0 : _d.call(track).deviceId) != null ? _e : "";
    if (track) {
      this.trackEndedHandler = () => void this.handleMicrophoneLost();
      track.addEventListener("ended", this.trackEndedHandler);
    }
    this.deviceChangeHandler = () => {
      void this.checkInputStillPresent();
    };
    navigator.mediaDevices.addEventListener("devicechange", this.deviceChangeHandler);
  }
  async checkInputStillPresent() {
    if (this.state !== "recording" || this.disconnectNotified) {
      return;
    }
    let devices;
    try {
      devices = await navigator.mediaDevices.enumerateDevices();
    } catch (error) {
      console.error(error);
      return;
    }
    const inputs = devices.filter((device) => device.kind === "audioinput");
    const stillPresent = this.activeDeviceId ? inputs.some((device) => device.deviceId === this.activeDeviceId) : inputs.length > 0;
    if (stillPresent) {
      return;
    }
    await this.handleMicrophoneLost();
  }
  async handleMicrophoneLost() {
    var _a;
    if (!["recording", "paused"].includes(this.state) || this.disconnectNotified) return;
    this.disconnectNotified = true;
    this.manuallyPaused = false;
    if (this.pausedAt === null) this.pausedAt = Date.now();
    if (((_a = this.mediaRecorder) == null ? void 0 : _a.state) === "recording") {
      this.mediaRecorder.requestData();
      this.mediaRecorder.pause();
    }
    this.stopSilenceWatch();
    this.state = "recovering";
    this.handlers.onStateChange("recovering", "Microphone access was interrupted. Reconnecting\u2026");
    await this.recoverMicrophone();
  }
  async recoverMicrophone() {
    this.state = "recovering";
    this.handlers.onStateChange("recovering", "Restoring microphone access\u2026");
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const previousRecorder = this.mediaRecorder;
      if (previousRecorder && previousRecorder.state !== "inactive") {
        previousRecorder.onstop = null;
        previousRecorder.stop();
      }
      if (this.mediaStream) this.mediaStream.getTracks().forEach((track) => track.stop());
      this.mediaStream = stream;
      const options = this.selectedMime ? { mimeType: this.selectedMime.mime } : void 0;
      const recorder = new MediaRecorder(stream, options);
      recorder.ondataavailable = (event) => {
        var _a;
        if ((_a = event.data) == null ? void 0 : _a.size) this.chunks.push(event.data);
      };
      recorder.onstop = () => this.finalize();
      this.mediaRecorder = recorder;
      recorder.start();
      this.disconnectNotified = false;
      this.finishPauseTiming();
      this.state = "recording";
      this.watchSilence();
      this.watchDeviceChanges();
      this.handlers.onStateChange("recording", "Transcription resumed.");
    } catch (error) {
      console.error(error);
      this.state = "error";
      this.handlers.onStateChange("error", "Microphone could not be restored. Use Resume to try again.");
    }
  }
  finishPauseTiming() {
    if (this.pausedAt !== null) {
      this.totalPausedMs += Date.now() - this.pausedAt;
      this.pausedAt = null;
    }
  }
};
function pickMimeType() {
  for (const candidate of MIME_CANDIDATES) {
    if (MediaRecorder.isTypeSupported(candidate.mime)) {
      return candidate;
    }
  }
  return null;
}
function extensionFromMime(mimeType) {
  if (mimeType.includes("mp4")) return "m4a";
  if (mimeType.includes("aac")) return "aac";
  if (mimeType.includes("ogg")) return "ogg";
  if (mimeType.includes("webm")) return "webm";
  return "audio";
}
function sleep(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}
function getErrorText(error) {
  return error instanceof Error ? error.message : String(error);
}

// src/waveform.ts
var WaveformView = class {
  constructor(container, getAnalyser) {
    this.container = container;
    this.getAnalyser = getAnalyser;
    this.rafId = null;
    this.data = null;
    this.canvas = container.createEl("canvas", { cls: "flux-tts-waveform-canvas" });
    this.ctx = this.canvas.getContext("2d");
  }
  /** Begin animating. Safe to call when already running. */
  start() {
    if (this.rafId !== null) {
      return;
    }
    this.container.toggleClass("is-recording", true);
    const loop = () => {
      this.draw();
      this.rafId = window.requestAnimationFrame(loop);
    };
    this.rafId = window.requestAnimationFrame(loop);
  }
  /** Stop animating and clear the canvas. Safe to call when already stopped. */
  stop() {
    if (this.rafId !== null) {
      window.cancelAnimationFrame(this.rafId);
      this.rafId = null;
    }
    this.container.toggleClass("is-recording", false);
    this.clear();
  }
  /** Remove the canvas from the DOM (plugin unload). */
  dispose() {
    this.stop();
    this.canvas.remove();
  }
  draw() {
    const ctx = this.ctx;
    if (!ctx) {
      return;
    }
    const { width, height } = this.syncCanvasSize();
    ctx.clearRect(0, 0, width, height);
    const analyser = this.getAnalyser();
    ctx.fillStyle = this.strokeColor();
    if (!analyser) {
      ctx.fillRect(0, Math.floor(height / 2), width, Math.max(1, Math.floor(height / 12)));
      return;
    }
    const bins = analyser.fftSize;
    if (!this.data || this.data.length !== bins) {
      this.data = new Uint8Array(new ArrayBuffer(bins));
    }
    const data = this.data;
    analyser.getByteTimeDomainData(data);
    const barCount = Math.max(12, Math.min(48, Math.floor(width / 6)));
    const gap = Math.max(1, Math.floor(width / barCount / 4));
    const barWidth = Math.max(1, width / barCount - gap);
    const samplesPerBar = Math.max(1, Math.floor(bins / barCount));
    for (let bar = 0; bar < barCount; bar += 1) {
      let peak = 0;
      const start = bar * samplesPerBar;
      for (let index = start; index < Math.min(bins, start + samplesPerBar); index += 1) {
        peak = Math.max(peak, Math.abs(data[index] - 128) / 128);
      }
      const barHeight = Math.max(2, peak * height);
      ctx.fillRect(bar * (barWidth + gap), (height - barHeight) / 2, barWidth, barHeight);
    }
  }
  /** Match the backing store to the element's CSS size (crisp on HiDPI). */
  syncCanvasSize() {
    const dpr = window.devicePixelRatio || 1;
    const cssWidth = this.canvas.clientWidth || this.container.clientWidth || 80;
    const cssHeight = this.canvas.clientHeight || this.container.clientHeight || 20;
    const width = Math.max(1, Math.round(cssWidth * dpr));
    const height = Math.max(1, Math.round(cssHeight * dpr));
    if (this.canvas.width !== width) {
      this.canvas.width = width;
    }
    if (this.canvas.height !== height) {
      this.canvas.height = height;
    }
    return { width, height };
  }
  clear() {
    if (this.ctx) {
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    }
  }
  strokeColor() {
    const color = window.getComputedStyle(this.canvas).color;
    return color || "#888";
  }
};

// src/transcription.ts
var import_obsidian4 = require("obsidian");
var GROQ_TRANSCRIPTION_URL = "https://api.groq.com/openai/v1/audio/transcriptions";
var GROQ_CHAT_URL = "https://api.groq.com/openai/v1/chat/completions";
var CLEANUP_MODEL = "llama-3.3-70b-versatile";
var CLEANUP_SYSTEM_PROMPT = "You clean up raw speech-to-text transcripts. Fix punctuation and capitalization, remove filler words (um, uh, you know, like when used as filler), and break the text into readable paragraphs. Do not summarize, rephrase, add, or remove any substantive content. Return only the cleaned transcript with no preamble or commentary.";
var SPEECH_WORDS_PER_MINUTE = 150;
var LENGTH_CHECK_MIN_SECONDS = 15;
var LENGTH_CHECK_MIN_RATIO = 0.3;
async function transcribeAudio(options) {
  var _a, _b;
  const boundary = `----flux-tts-${Date.now().toString(36)}`;
  const body = await buildMultipartBody(boundary, [
    { name: "model", value: options.model },
    { name: "response_format", value: options.wantSegments ? "verbose_json" : "text" },
    {
      name: "file",
      fileName: options.fileName,
      contentType: options.blob.type || "application/octet-stream",
      value: await options.blob.arrayBuffer()
    }
  ]);
  const response = await (0, import_obsidian4.requestUrl)({
    url: GROQ_TRANSCRIPTION_URL,
    method: "POST",
    contentType: `multipart/form-data; boundary=${boundary}`,
    headers: {
      Authorization: `Bearer ${options.apiKey}`
    },
    body,
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Groq returned HTTP ${response.status}: ${response.text}`);
  }
  if (!options.wantSegments) {
    return { text: response.text, segments: [] };
  }
  const parsed = JSON.parse(response.text);
  return {
    text: String((_a = parsed.text) != null ? _a : ""),
    segments: ((_b = parsed.segments) != null ? _b : []).map((segment) => {
      var _a2;
      return {
        start: Number(segment.start) || 0,
        end: Number(segment.end) || 0,
        text: String((_a2 = segment.text) != null ? _a2 : "")
      };
    })
  };
}
async function cleanupTranscript(apiKey, transcript) {
  var _a, _b, _c;
  const response = await (0, import_obsidian4.requestUrl)({
    url: GROQ_CHAT_URL,
    method: "POST",
    contentType: "application/json",
    headers: {
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: CLEANUP_MODEL,
      temperature: 0.2,
      messages: [
        { role: "system", content: CLEANUP_SYSTEM_PROMPT },
        { role: "user", content: transcript }
      ]
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Groq returned HTTP ${response.status}: ${response.text}`);
  }
  const parsed = response.json;
  const content = (_c = (_b = (_a = parsed == null ? void 0 : parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  if (typeof content !== "string" || !content.trim()) {
    throw new Error("Transcript cleanup returned no content.");
  }
  return content.trim();
}
function renderSegmentedTranscript(segments, audioPath) {
  return segments.map((segment) => {
    const seconds = Math.max(0, Math.floor(segment.start));
    const label = formatTimestamp(segment.start);
    return `[[${audioPath}#t=${seconds}|${label}]] ${segment.text.trim()}`;
  }).join("\n\n");
}
function transcriptLengthWarning(transcript, durationSeconds) {
  if (durationSeconds < LENGTH_CHECK_MIN_SECONDS) {
    return null;
  }
  const wordCount = transcript.split(/\s+/).filter(Boolean).length;
  const expectedSeconds = wordCount / SPEECH_WORDS_PER_MINUTE * 60;
  if (expectedSeconds >= durationSeconds * LENGTH_CHECK_MIN_RATIO) {
    return null;
  }
  const duration = formatTimestamp(durationSeconds);
  return `

> [!warning] This transcript seems short for a ${duration} recording \u2014 worth checking the audio.`;
}
function formatTimestamp(totalSeconds) {
  const whole = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(whole / 3600);
  const minutes = Math.floor(whole % 3600 / 60);
  const seconds = whole % 60;
  const pad = (value) => String(value).padStart(2, "0");
  return hours > 0 ? `${hours}:${pad(minutes)}:${pad(seconds)}` : `${minutes}:${pad(seconds)}`;
}
async function buildMultipartBody(boundary, parts) {
  const encoder = new TextEncoder();
  const chunks = [];
  for (const part of parts) {
    let header = `--${boundary}\r
Content-Disposition: form-data; name="${part.name}"`;
    if (part.fileName) {
      header += `; filename="${part.fileName}"`;
    }
    header += "\r\n";
    if (part.contentType) {
      header += `Content-Type: ${part.contentType}\r
`;
    }
    header += "\r\n";
    chunks.push(encoder.encode(header));
    chunks.push(part.value instanceof ArrayBuffer ? new Uint8Array(part.value) : encoder.encode(String(part.value)));
    chunks.push(encoder.encode("\r\n"));
  }
  chunks.push(encoder.encode(`--${boundary}--\r
`));
  return concatChunks(chunks);
}
function concatChunks(chunks) {
  const totalLength = chunks.reduce((total, chunk) => total + chunk.byteLength, 0);
  const output = new Uint8Array(totalLength);
  let offset = 0;
  for (const chunk of chunks) {
    output.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return output.buffer;
}

// src/paths.ts
var import_obsidian5 = require("obsidian");
function getAttachmentFolder(app) {
  var _a, _b;
  const configured = (_b = (_a = app.vault).getConfig) == null ? void 0 : _b.call(
    _a,
    "attachmentFolderPath"
  );
  if (typeof configured === "string" && configured.trim()) {
    return sanitizeFolderPath(configured);
  }
  return "";
}
function resolveAudioPath(app, settings, fileName) {
  const cleanFileName = sanitizeFileName(fileName);
  if (settings.saveLocation === "root") {
    return cleanFileName;
  }
  if (settings.saveLocation === "attachments") {
    const attachmentFolder = getAttachmentFolder(app);
    if (attachmentFolder) {
      return (0, import_obsidian5.normalizePath)(`${attachmentFolder}/${cleanFileName}`);
    }
    new import_obsidian5.Notice("No Obsidian attachment folder is configured; saving audio at vault root.");
    return cleanFileName;
  }
  const folder = sanitizeFolderPath(settings.audioFolder) || DEFAULT_SETTINGS.audioFolder;
  return (0, import_obsidian5.normalizePath)(`${folder}/${cleanFileName}`);
}
function resolveNotePath(app, settings, fileName) {
  const cleanFileName = sanitizeFileName(fileName);
  if (settings.noteFolderMode === "attachments") {
    const attachmentFolder = getAttachmentFolder(app);
    if (attachmentFolder) {
      return (0, import_obsidian5.normalizePath)(`${attachmentFolder}/${cleanFileName}`);
    }
    new import_obsidian5.Notice("No Obsidian attachment folder is configured; creating the note at vault root.");
    return cleanFileName;
  }
  if (settings.noteFolderMode === "custom") {
    const folder = sanitizeFolderPath(settings.noteFolder);
    if (folder) {
      return (0, import_obsidian5.normalizePath)(`${folder}/${cleanFileName}`);
    }
  }
  return cleanFileName;
}
function resolveRecordingNotePath(app, settings) {
  const fileName = "Recording....md";
  if (settings.recordingNoteFolderMode === "attachments") {
    const folder = getAttachmentFolder(app);
    if (folder) return (0, import_obsidian5.normalizePath)(`${folder}/${fileName}`);
    new import_obsidian5.Notice("No Obsidian attachment folder is configured; creating Recording... at the vault root.");
  }
  if (settings.recordingNoteFolderMode === "custom") {
    const folder = sanitizeFolderPath(settings.recordingNoteFolder);
    if (folder) return (0, import_obsidian5.normalizePath)(`${folder}/${fileName}`);
  }
  return fileName;
}
async function ensureParentFolder(app, path) {
  const folder = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
  if (folder) {
    await ensureFolder(app, folder);
  }
}
async function ensureFolder(app, path) {
  const normalized = (0, import_obsidian5.normalizePath)(path);
  if (!normalized || app.vault.getAbstractFileByPath(normalized)) {
    return;
  }
  const parts = normalized.split("/");
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(current)) {
      await app.vault.createFolder(current);
    }
  }
}
async function uniquePath(app, path, extension) {
  const normalized = (0, import_obsidian5.normalizePath)(path);
  if (!app.vault.getAbstractFileByPath(normalized)) {
    return normalized;
  }
  const base = extension && normalized.toLowerCase().endsWith(extension.toLowerCase()) ? normalized.slice(0, -extension.length) : normalized;
  const suffix = extension && normalized.toLowerCase().endsWith(extension.toLowerCase()) ? extension : "";
  for (let index = 2; index < 1e3; index += 1) {
    const candidate = `${base} ${index}${suffix}`;
    if (!app.vault.getAbstractFileByPath(candidate)) {
      return candidate;
    }
  }
  throw new Error(`Could not find an available filename for ${normalized}`);
}
async function writeBinaryUnique(app, path, extension, buffer) {
  await ensureParentFolder(app, path);
  const target = await uniquePath(app, path, extension);
  await app.vault.createBinary(target, buffer);
  return target;
}
async function createNoteUnique(app, path, content) {
  await ensureParentFolder(app, path);
  const target = await uniquePath(app, path, ".md");
  await app.vault.create(target, content);
  return target;
}

// src/media.ts
var import_obsidian6 = require("obsidian");
var MAX_MEDIA_BYTES = 25 * 1024 * 1024;
function extractMediaUrl(text) {
  var _a;
  const matches = (_a = text.match(/https?:\/\/[^\s<>]+/g)) != null ? _a : [];
  for (const raw of matches) {
    const candidate = raw.replace(/[),.;!?]+$/, "");
    try {
      const url = new URL(candidate);
      if (["http:", "https:"].includes(url.protocol)) return url.href;
    } catch (e) {
    }
  }
  return null;
}
async function fetchMediaTranscript(options) {
  const youtubeId = getYouTubeId(options.url);
  if (youtubeId) {
    const captions = await fetchYouTubeCaptions(options.url);
    if (captions) return captions;
  }
  const media = await resolveMediaAsset(options.url);
  if (!options.apiKey) {
    throw new Error("This link has no accessible captions. Add a Groq API key to transcribe its media.");
  }
  if (media.data.byteLength > MAX_MEDIA_BYTES) {
    throw new Error("The linked media is larger than the 25 MB transcription limit.");
  }
  const transcription = await transcribeAudio({
    apiKey: options.apiKey,
    model: options.model,
    blob: new Blob([media.data], { type: media.contentType }),
    fileName: media.fileName,
    wantSegments: options.wantSegments
  });
  return { ...transcription, title: media.title, sourceUrl: options.url };
}
async function fetchYouTubeCaptions(url) {
  var _a, _b;
  const page = await (0, import_obsidian6.requestUrl)({ url, throw: false });
  if (page.status < 200 || page.status >= 300) throw new Error(`YouTube returned HTTP ${page.status}.`);
  const tracksMatch = page.text.match(/"captionTracks":(\[.*?\]),"audioTracks"/s);
  if (!tracksMatch) return null;
  let tracks;
  try {
    tracks = JSON.parse(tracksMatch[1]);
  } catch (e) {
    return null;
  }
  const track = tracks.find((item) => item.baseUrl);
  if (!(track == null ? void 0 : track.baseUrl)) return null;
  const captionResponse = await (0, import_obsidian6.requestUrl)({ url: `${track.baseUrl}&fmt=json3`, throw: false });
  if (captionResponse.status < 200 || captionResponse.status >= 300) return null;
  const parsed = captionResponse.json;
  const segments = ((_a = parsed.events) != null ? _a : []).map((event) => {
    var _a2, _b2, _c, _d;
    return {
      start: ((_a2 = event.tStartMs) != null ? _a2 : 0) / 1e3,
      end: (((_b2 = event.tStartMs) != null ? _b2 : 0) + ((_c = event.dDurationMs) != null ? _c : 0)) / 1e3,
      text: ((_d = event.segs) != null ? _d : []).map((segment) => {
        var _a3;
        return (_a3 = segment.utf8) != null ? _a3 : "";
      }).join("").replace(/\s+/g, " ").trim()
    };
  }).filter((segment) => segment.text);
  if (!segments.length) return null;
  const titleMatch = page.text.match(/<title>(.*?)<\/title>/is);
  const title = decodeHtml(((_b = titleMatch == null ? void 0 : titleMatch[1]) == null ? void 0 : _b.replace(/\s*-\s*YouTube\s*$/, "").trim()) || "YouTube video");
  return { title, sourceUrl: url, text: segments.map((segment) => segment.text).join(" "), segments };
}
async function resolveMediaAsset(url) {
  var _a, _b, _c;
  const first = await (0, import_obsidian6.requestUrl)({ url, throw: false });
  if (first.status < 200 || first.status >= 300) throw new Error(`Media link returned HTTP ${first.status}.`);
  const contentType = (_b = (_a = first.headers["content-type"]) == null ? void 0 : _a.split(";")[0]) != null ? _b : "";
  if (contentType.startsWith("audio/") || contentType.startsWith("video/")) {
    return mediaResponse(url, first.arrayBuffer, contentType, "Linked media");
  }
  const mediaUrl = findMetaContent(first.text, "og:video") || findMetaContent(first.text, "og:audio");
  if (!mediaUrl) throw new Error("No public captions or downloadable audio/video were found at this link.");
  const second = await (0, import_obsidian6.requestUrl)({ url: new URL(mediaUrl, url).href, throw: false });
  if (second.status < 200 || second.status >= 300) throw new Error(`Linked media returned HTTP ${second.status}.`);
  const mediaType = ((_c = second.headers["content-type"]) == null ? void 0 : _c.split(";")[0]) || "application/octet-stream";
  return mediaResponse(mediaUrl, second.arrayBuffer, mediaType, decodeHtml(findMetaContent(first.text, "og:title") || "Linked media"));
}
function mediaResponse(url, data, contentType, title) {
  var _a;
  const extension = ((_a = contentType.split("/")[1]) == null ? void 0 : _a.replace(/[^a-z0-9]/gi, "")) || "media";
  let fileName = `media.${extension}`;
  try {
    fileName = new URL(url).pathname.split("/").pop() || fileName;
  } catch (e) {
  }
  return { data, contentType, fileName, title };
}
function getYouTubeId(url) {
  var _a;
  try {
    const parsed = new URL(url);
    if (parsed.hostname === "youtu.be") return parsed.pathname.slice(1).split("/")[0] || null;
    if (parsed.hostname.endsWith("youtube.com")) {
      if (parsed.pathname === "/watch") return parsed.searchParams.get("v");
      const match = parsed.pathname.match(/^\/(?:shorts|embed)\/([^/]+)/);
      return (_a = match == null ? void 0 : match[1]) != null ? _a : null;
    }
  } catch (e) {
    return null;
  }
  return null;
}
function findMetaContent(html, property) {
  const escaped = property.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const forward = html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["']`, "i"));
  const reverse = html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["']`, "i"));
  return decodeHtml((forward == null ? void 0 : forward[1]) || (reverse == null ? void 0 : reverse[1]) || "") || null;
}
function decodeHtml(value) {
  return value.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}

// src/recording-ui-state.ts
function recordingAction(state) {
  if (state === "paused" || state === "error") {
    return { label: "Resume transcription", active: false, icon: "play" };
  }
  if (state === "starting" || state === "recording" || state === "recovering") {
    return { label: "Stop transcription", active: true, icon: "square" };
  }
  return { label: "Start transcription", active: false, icon: "mic" };
}
function createRetryBlock(data) {
  return `\`\`\`flux-tts-retry
${JSON.stringify(data)}
\`\`\``;
}
function parseRetryBlock(source) {
  const parsed = JSON.parse(source);
  if (typeof parsed.audioPath !== "string" || !parsed.audioPath) throw new Error("Missing audio path.");
  if (typeof parsed.fileName !== "string" || !parsed.fileName) throw new Error("Missing audio filename.");
  return {
    audioPath: parsed.audioPath,
    fileName: parsed.fileName,
    message: typeof parsed.message === "string" && parsed.message ? parsed.message : "Transcription failed."
  };
}

// src/main.ts
var PLUGIN_ID = "flux-tts";
var SECRET_KEY = `${PLUGIN_ID}-groq-api-key`;
function getErrorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}
function mimeFromFileName(fileName) {
  var _a;
  const extension = (_a = fileName.split(".").pop()) == null ? void 0 : _a.toLowerCase();
  if (extension === "m4a" || extension === "mp4") return "audio/mp4";
  if (extension === "aac") return "audio/aac";
  if (extension === "ogg") return "audio/ogg";
  return "audio/webm";
}
var FluxTtsPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.recorder = null;
    this.ribbonIconEl = null;
    this.waveform = null;
    this.waveformFloatEl = null;
    this.inlineSession = null;
    this.recordingNoteLeaf = null;
    this.recordingNoteUi = null;
    this.recordingNoteWaveform = null;
    this.recordingStateEl = null;
    this.recordingResumeButton = null;
    this.pausedForBackground = false;
  }
  async onload() {
    await this.loadSettings();
    this.recorder = new RecorderController({
      onFinish: (result) => {
        this.handleRecordingFinished(result).catch((error) => {
          console.error(error);
          new import_obsidian7.Notice(`Recording failed: ${getErrorMessage(error)}`);
        });
      },
      onError: (error) => {
        console.error(error);
        new import_obsidian7.Notice(error.message);
      },
      onStateChange: (state, message) => this.handleRecorderState(state, message)
    });
    this.ribbonIconEl = this.addRibbonIcon("mic", "Start transcription", () => {
      void this.toggleRecording();
    });
    this.addCommand({
      id: "toggle-recording",
      name: "Toggle recording",
      callback: () => void this.toggleRecording()
    });
    this.addCommand({
      id: "start-recording",
      name: "Start recording",
      callback: () => {
        var _a;
        if ((_a = this.recorder) == null ? void 0 : _a.isActive) {
          new import_obsidian7.Notice("Already recording.");
          return;
        }
        void this.startRecording();
      }
    });
    this.addCommand({
      id: "stop-recording",
      name: "Stop recording",
      callback: () => {
        var _a;
        if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) {
          new import_obsidian7.Notice("Not recording.");
          return;
        }
        this.stopRecording();
      }
    });
    this.addCommand({
      id: "cycle-transcription-model",
      name: "Cycle transcription model",
      callback: async () => {
        const index = GROQ_MODELS.findIndex((model) => model.id === this.settings.model);
        const next = GROQ_MODELS[(index + 1) % GROQ_MODELS.length];
        this.settings.model = next.id;
        await this.saveSettings();
        new import_obsidian7.Notice(`Transcription model: ${next.name}`);
      }
    });
    this.addCommand({
      id: "toggle-inline-transcription",
      name: "Toggle inline transcription (at cursor)",
      callback: () => void this.toggleInlineRecording()
    });
    this.addCommand({
      id: "start-inline-transcription",
      name: "Start inline transcription (at cursor)",
      callback: () => {
        var _a;
        if ((_a = this.recorder) == null ? void 0 : _a.isActive) {
          new import_obsidian7.Notice("Already recording.");
          return;
        }
        void this.startInlineRecording();
      }
    });
    this.addCommand({
      id: "stop-inline-transcription",
      name: "Stop inline transcription",
      callback: () => {
        var _a;
        if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) {
          new import_obsidian7.Notice("Not recording.");
          return;
        }
        this.stopRecording();
      }
    });
    this.addSettingTab(new FluxTtsSettingTab(this.app, this));
    this.registerMarkdownCodeBlockProcessor("flux-tts-retry", (source, element, context) => {
      this.renderRetryBlock(source, element, context.sourcePath);
    });
    this.registerEvent(
      this.app.workspace.on("editor-paste", (event, editor) => {
        var _a, _b;
        if (event.defaultPrevented) return;
        if (!this.settings.autoMediaTranscripts) return;
        const pastedText = (_b = (_a = event.clipboardData) == null ? void 0 : _a.getData("text/plain")) != null ? _b : "";
        const mediaUrl = extractMediaUrl(pastedText);
        if (!mediaUrl) return;
        event.preventDefault();
        const footnoteId = `media-${Date.now().toString(36)}`;
        editor.replaceSelection(`${pastedText} [^${footnoteId}]`);
        void this.insertMediaTranscript(editor, footnoteId, mediaUrl);
      })
    );
    this.registerDomEvent(activeDocument, "visibilitychange", () => {
      var _a;
      if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) return;
      if (activeDocument.hidden && this.recorder.isRecording) {
        this.pausedForBackground = true;
        this.recorder.pause("Transcription paused while Obsidian is in the background.");
      } else if (!activeDocument.hidden && this.pausedForBackground) {
        this.pausedForBackground = false;
        void this.recorder.resume().catch((error) => {
          console.error(error);
          new import_obsidian7.Notice(`Could not resume recording: ${getErrorMessage(error)}`);
        });
      }
    });
    this.setupWaveform();
    this.updateRibbonState(false);
  }
  onunload() {
    var _a, _b, _c;
    (_a = this.recorder) == null ? void 0 : _a.dispose();
    this.recorder = null;
    (_b = this.waveform) == null ? void 0 : _b.dispose();
    this.waveform = null;
    (_c = this.waveformFloatEl) == null ? void 0 : _c.remove();
    this.waveformFloatEl = null;
    this.closeRecordingNote();
  }
  /**
   * Create the live-waveform view. Desktop has a status bar to host it; mobile
   * doesn't, so we use a floating pill that CSS reveals only while recording.
   */
  setupWaveform() {
    let container;
    if (import_obsidian7.Platform.isMobile) {
      this.waveformFloatEl = activeDocument.body.createDiv({ cls: "flux-tts-waveform-float" });
      container = this.waveformFloatEl;
    } else {
      container = this.addStatusBarItem();
      container.addClass("flux-tts-waveform-status");
    }
    this.waveform = new WaveformView(container, () => {
      var _a, _b;
      return (_b = (_a = this.recorder) == null ? void 0 : _a.getAnalyser()) != null ? _b : null;
    });
  }
  async loadSettings() {
    var _a;
    const saved = (_a = await this.loadData()) != null ? _a : {};
    if (!saved.noteFolderMode) {
      saved.noteFolderMode = typeof saved.noteFolder === "string" && saved.noteFolder.trim() ? "custom" : "root";
    }
    delete saved.noteTemplate;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
    this.validateSettings();
  }
  async saveSettings() {
    this.validateSettings();
    await this.saveData(this.settings);
  }
  validateSettings() {
    if (!GROQ_MODELS.some((model) => model.id === this.settings.model)) {
      this.settings.model = DEFAULT_SETTINGS.model;
    }
    if (!["audio-folder", "attachments", "root"].includes(this.settings.saveLocation)) {
      this.settings.saveLocation = DEFAULT_SETTINGS.saveLocation;
    }
    if (!["root", "attachments", "custom"].includes(this.settings.noteFolderMode)) {
      this.settings.noteFolderMode = DEFAULT_SETTINGS.noteFolderMode;
    }
    const stringKeys = [
      "audioFolder",
      "noteFolder",
      "recordingNoteFolder",
      "audioNameTemplate",
      "noteNameTemplate",
      "noteTemplatePath"
    ];
    for (const key of stringKeys) {
      if (typeof this.settings[key] !== "string") {
        this.settings[key] = DEFAULT_SETTINGS[key];
      }
    }
    for (const key of ["audioNameTemplate", "noteNameTemplate"]) {
      if (!validateTemplate(this.settings[key], FILENAME_TEMPLATE_KEYS).valid) {
        this.settings[key] = DEFAULT_SETTINGS[key];
      }
    }
    const delay = Number(this.settings.startDelayMs);
    this.settings.startDelayMs = Number.isFinite(delay) ? Math.min(2e3, Math.max(0, Math.round(delay))) : 0;
    this.settings.useTemplate = Boolean(this.settings.useTemplate);
    this.settings.cleanupTranscript = Boolean(this.settings.cleanupTranscript);
    this.settings.segmentedTranscript = Boolean(this.settings.segmentedTranscript);
    this.settings.autoMediaTranscripts = Boolean(this.settings.autoMediaTranscripts);
    this.settings.recordingNoteEnabled = Boolean(this.settings.recordingNoteEnabled);
    if (!["root", "attachments", "custom"].includes(this.settings.recordingNoteFolderMode)) {
      this.settings.recordingNoteFolderMode = DEFAULT_SETTINGS.recordingNoteFolderMode;
    }
    if (!["reuse", "recreate"].includes(this.settings.recordingNoteBehavior)) {
      this.settings.recordingNoteBehavior = DEFAULT_SETTINGS.recordingNoteBehavior;
    }
  }
  async insertMediaTranscript(editor, footnoteId, mediaUrl) {
    new import_obsidian7.Notice("Fetching media transcript\u2026");
    try {
      const result = await fetchMediaTranscript({
        url: mediaUrl,
        apiKey: this.getApiKey(),
        model: this.settings.model,
        wantSegments: this.settings.segmentedTranscript
      });
      let transcript = result.text.trim();
      if (this.settings.cleanupTranscript && !this.settings.segmentedTranscript && this.getApiKey()) {
        transcript = await cleanupTranscript(this.getApiKey(), transcript);
      }
      const indented = transcript.replace(/\n+/g, "\n    ");
      const label = result.title.replace(/\[|\]/g, "");
      const footnote = `

[^${footnoteId}]: **[${label}](${result.sourceUrl})** \u2014 transcript
    ${indented}`;
      const lastLine = editor.lastLine();
      editor.replaceRange(footnote, { line: lastLine, ch: editor.getLine(lastLine).length });
      new import_obsidian7.Notice("Media transcript added.");
    } catch (error) {
      const message = getErrorMessage(error);
      const lastLine = editor.lastLine();
      const footnote = `

[^${footnoteId}]: Transcript unavailable \u2014 ${message}`;
      editor.replaceRange(footnote, { line: lastLine, ch: editor.getLine(lastLine).length });
      new import_obsidian7.Notice(`Could not transcribe media link: ${message}`);
    }
  }
  async toggleRecording() {
    var _a, _b, _c;
    if (((_a = this.recorder) == null ? void 0 : _a.currentState) === "paused" || ((_b = this.recorder) == null ? void 0 : _b.currentState) === "error") {
      await this.recorder.resume();
      return;
    }
    if ((_c = this.recorder) == null ? void 0 : _c.isActive) {
      this.stopRecording();
      return;
    }
    await this.startRecording();
  }
  async startRecording() {
    var _a;
    if (!this.recorder || this.recorder.isActive) {
      return;
    }
    if (!((_a = navigator.mediaDevices) == null ? void 0 : _a.getUserMedia) || typeof MediaRecorder === "undefined") {
      new import_obsidian7.Notice("Audio recording is not available in this Obsidian environment.");
      return;
    }
    if (!this.getApiKey()) {
      new import_obsidian7.Notice("Add your Groq API key in Flux TTS settings first.");
      return;
    }
    try {
      if (this.settings.recordingNoteEnabled && !this.inlineSession) {
        await this.openRecordingNote();
      }
      await this.recorder.start(this.settings.startDelayMs);
      if (this.recorder.isRecording) {
        new import_obsidian7.Notice("Recording started.");
      }
    } catch (error) {
      this.closeRecordingNote();
      console.error(error);
      new import_obsidian7.Notice(`Could not start recording: ${getErrorMessage(error)}`);
    }
  }
  stopRecording() {
    var _a;
    if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) {
      return;
    }
    const wasRecording = this.recorder.isRecording;
    this.recorder.stop();
    this.closeRecordingNote();
    if (wasRecording) {
      new import_obsidian7.Notice("Saving and transcribing...");
    }
  }
  async openRecordingNote() {
    const path = resolveRecordingNotePath(this.app, this.settings);
    await ensureParentFolder(this.app, path);
    let file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian7.TFile && this.settings.recordingNoteBehavior === "recreate") {
      await this.app.vault.delete(file);
      file = null;
    }
    if (!(file instanceof import_obsidian7.TFile)) {
      file = await this.app.vault.create(path, "# Recording...\n");
    }
    if (!(file instanceof import_obsidian7.TFile)) throw new Error(`Could not open ${path}.`);
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file);
    this.recordingNoteLeaf = leaf;
    const view = leaf.view;
    if (!(view instanceof import_obsidian7.MarkdownView)) return;
    const ui = view.contentEl.createDiv({ cls: "flux-tts-recording-note" });
    const waveformHost = ui.createDiv({ cls: "flux-tts-recording-note-waveform" });
    this.recordingNoteWaveform = new WaveformView(waveformHost, () => {
      var _a, _b;
      return (_b = (_a = this.recorder) == null ? void 0 : _a.getAnalyser()) != null ? _b : null;
    });
    this.recordingStateEl = ui.createDiv({ cls: "flux-tts-recording-state", text: "Starting microphone\u2026" });
    const actions = ui.createDiv({ cls: "flux-tts-recording-actions" });
    this.recordingResumeButton = actions.createEl("button", { text: "Resume", cls: "mod-cta" });
    this.recordingResumeButton.hide();
    this.recordingResumeButton.addEventListener("click", () => {
      var _a;
      return void ((_a = this.recorder) == null ? void 0 : _a.resume());
    });
    const stopButton = actions.createEl("button", { text: "Stop" });
    stopButton.addEventListener("click", () => this.stopRecording());
    this.recordingNoteUi = ui;
  }
  closeRecordingNote() {
    var _a, _b, _c;
    (_a = this.recordingNoteWaveform) == null ? void 0 : _a.dispose();
    this.recordingNoteWaveform = null;
    (_b = this.recordingNoteUi) == null ? void 0 : _b.remove();
    this.recordingNoteUi = null;
    this.recordingStateEl = null;
    this.recordingResumeButton = null;
    (_c = this.recordingNoteLeaf) == null ? void 0 : _c.detach();
    this.recordingNoteLeaf = null;
  }
  handleRecorderState(state, message) {
    var _a, _b;
    const action = recordingAction(state);
    this.updateRibbonState(action.active, action.label, action.icon);
    if (state === "recording") (_a = this.recordingNoteWaveform) == null ? void 0 : _a.start();
    else (_b = this.recordingNoteWaveform) == null ? void 0 : _b.stop();
    if (this.recordingStateEl) {
      const fallback = {
        idle: "Stopped",
        starting: "Starting microphone\u2026",
        recording: "Recording",
        paused: "Paused",
        recovering: "Restoring microphone access\u2026",
        error: "Microphone unavailable"
      };
      this.recordingStateEl.setText(message || fallback[state]);
    }
    if (this.recordingResumeButton) {
      this.recordingResumeButton.toggle(state === "paused" || state === "error");
    }
    if (message && state === "error") new import_obsidian7.Notice(message);
    if (state === "idle") this.closeRecordingNote();
  }
  async toggleInlineRecording() {
    var _a;
    if ((_a = this.recorder) == null ? void 0 : _a.isActive) {
      this.stopRecording();
      return;
    }
    await this.startInlineRecording();
  }
  /**
   * Start a recording that will be inserted at the cursor of the active note
   * (rather than creating a new note). A placeholder is dropped in immediately
   * so the insertion point survives any editing done while recording.
   */
  async startInlineRecording() {
    if (!this.recorder || this.recorder.isActive) {
      return;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
    if (!view) {
      new import_obsidian7.Notice("Open a note and place the cursor where the transcription should go.");
      return;
    }
    const editor = view.editor;
    const id = `flux-${Date.now().toString(36)}`;
    const placeholder = `\u27E8transcribing\u2026 ${id}\u27E9`;
    editor.replaceSelection(placeholder);
    this.inlineSession = { editor, id, placeholder };
    await this.startRecording();
    if (!this.recorder.isActive) {
      this.removeInlinePlaceholder(this.inlineSession);
      this.inlineSession = null;
    }
  }
  removeInlinePlaceholder(session) {
    const { editor, placeholder } = session;
    const content = editor.getValue();
    const index = content.indexOf(placeholder);
    if (index >= 0) {
      editor.replaceRange("", editor.offsetToPos(index), editor.offsetToPos(index + placeholder.length));
    }
  }
  async handleRecordingFinished(result) {
    const inline = this.inlineSession;
    this.inlineSession = null;
    if (inline) {
      await this.handleInlineFinished(result, inline);
      return;
    }
    const context = createTemplateContext(/* @__PURE__ */ new Date());
    const audioFileName = `${renderTemplate(this.settings.audioNameTemplate, context)}.${result.extension}`;
    const noteFileName = `${renderTemplate(this.settings.noteNameTemplate, context)}.md`;
    const audioPath = resolveAudioPath(this.app, this.settings, audioFileName);
    const notePath = resolveNotePath(this.app, this.settings, noteFileName);
    const audioBuffer = await result.blob.arrayBuffer();
    const savedAudioPath = await writeBinaryUnique(this.app, audioPath, `.${result.extension}`, audioBuffer);
    let rawTranscript = "";
    let segments = [];
    let transcriptionFailed = false;
    let transcriptionError = "Unknown transcription error.";
    const apiKey = this.getApiKey();
    try {
      if (!apiKey) {
        throw new Error("Missing Groq API key.");
      }
      const transcription = await transcribeAudio({
        apiKey,
        model: this.settings.model,
        blob: result.blob,
        fileName: audioFileName,
        wantSegments: this.settings.segmentedTranscript
      });
      rawTranscript = transcription.text.trim();
      segments = transcription.segments;
    } catch (error) {
      console.error(error);
      transcriptionFailed = true;
      transcriptionError = getErrorMessage(error);
      rawTranscript = `Transcription failed: ${transcriptionError}`;
      new import_obsidian7.Notice("Audio saved, but transcription failed.");
    }
    const useSegments = !transcriptionFailed && this.settings.segmentedTranscript && segments.length > 0;
    let displayTranscript = rawTranscript;
    let originalTranscript = "";
    if (!transcriptionFailed && this.settings.cleanupTranscript && !useSegments && rawTranscript) {
      try {
        displayTranscript = await cleanupTranscript(apiKey, rawTranscript);
        originalTranscript = rawTranscript;
      } catch (error) {
        console.error(error);
        new import_obsidian7.Notice("Transcript cleanup failed; using the raw transcript.");
      }
    }
    const retryBlock = createRetryBlock({
      audioPath: savedAudioPath,
      fileName: audioFileName,
      message: transcriptionError
    });
    const transcriptForNote = transcriptionFailed ? retryBlock : useSegments ? renderSegmentedTranscript(segments, savedAudioPath) : displayTranscript;
    let noteBody = await this.renderNote(transcriptForNote, savedAudioPath, context, originalTranscript);
    if (!transcriptionFailed) {
      const warning = transcriptLengthWarning(rawTranscript, result.durationSeconds);
      if (warning) {
        noteBody += warning;
      }
    }
    const createdNotePath = await createNoteUnique(this.app, notePath, noteBody);
    const file = this.app.vault.getAbstractFileByPath(createdNotePath);
    if (file instanceof import_obsidian7.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    }
    new import_obsidian7.Notice("Transcription saved.");
  }
  async handleInlineFinished(result, session) {
    const context = createTemplateContext(/* @__PURE__ */ new Date());
    const audioFileName = `${renderTemplate(this.settings.audioNameTemplate, context)}.${result.extension}`;
    const audioPath = resolveAudioPath(this.app, this.settings, audioFileName);
    const audioBuffer = await result.blob.arrayBuffer();
    const savedAudioPath = await writeBinaryUnique(this.app, audioPath, `.${result.extension}`, audioBuffer);
    const { text, failed } = await this.runInlineTranscription(result, audioFileName);
    try {
      this.insertInlineTranscript(session, text, savedAudioPath);
      new import_obsidian7.Notice(failed ? "Audio saved; transcription failed \u2014 see the note." : "Transcription inserted.");
    } catch (error) {
      console.error(error);
      this.removeInlinePlaceholder(session);
      new import_obsidian7.Notice(`Could not insert inline. Recording saved at ${savedAudioPath}.`);
    }
  }
  /** Save-path-free transcription for inline mode: no segments, cleanup if enabled. */
  async runInlineTranscription(result, audioFileName) {
    const apiKey = this.getApiKey();
    try {
      if (!apiKey) {
        throw new Error("Missing Groq API key.");
      }
      const transcription = await transcribeAudio({
        apiKey,
        model: this.settings.model,
        blob: result.blob,
        fileName: audioFileName,
        wantSegments: false
      });
      let text = transcription.text.trim();
      if (this.settings.cleanupTranscript && text) {
        try {
          text = await cleanupTranscript(apiKey, text);
        } catch (error) {
          console.error(error);
          new import_obsidian7.Notice("Transcript cleanup failed; using the raw transcript.");
        }
      }
      return { text, failed: false };
    } catch (error) {
      console.error(error);
      new import_obsidian7.Notice("Audio saved, but transcription failed.");
      return { text: `Transcription failed: ${getErrorMessage(error)}`, failed: true };
    }
  }
  /**
   * Replace the placeholder with the transcript plus a footnote reference, and
   * append the footnote definition (a link back to the recording) at the end of
   * the note. Obsidian renders `[^id]` as a Wikipedia-style superscript link.
   */
  insertInlineTranscript(session, text, audioPath) {
    const { editor, id, placeholder } = session;
    const replacement = `${text.trim()}[^${id}]`;
    const content = editor.getValue();
    const index = content.indexOf(placeholder);
    if (index >= 0) {
      editor.replaceRange(replacement, editor.offsetToPos(index), editor.offsetToPos(index + placeholder.length));
    } else {
      editor.replaceSelection(replacement);
    }
    const definition = `[^${id}]: [[${audioPath}]]`;
    const current = editor.getValue();
    const separator = current.endsWith("\n\n") ? "" : current.endsWith("\n") ? "\n" : "\n\n";
    const lastLine = editor.lastLine();
    const endPos = { line: lastLine, ch: editor.getLine(lastLine).length };
    editor.replaceRange(`${separator}${definition}
`, endPos);
  }
  async renderNote(transcript, audioPath, context, originalTranscript) {
    const values = Object.assign({}, context, {
      transcript: transcript.trim(),
      audioPath,
      audioEmbed: `![[${audioPath}]]`,
      originalTranscript: originalTranscript.trim()
    });
    if (this.settings.useTemplate && this.settings.noteTemplatePath) {
      const template = await this.readNoteTemplate(this.settings.noteTemplatePath);
      if (template !== null) {
        return renderTemplate(template, values).trim();
      }
      new import_obsidian7.Notice(`Note template file not found: ${this.settings.noteTemplatePath}. Using the default layout.`);
    }
    let body = `${values.transcript}

${values.audioEmbed}`;
    if (values.originalTranscript) {
      body += `

## Original transcript

${values.originalTranscript}`;
    }
    return body;
  }
  renderRetryBlock(source, element, notePath) {
    let data;
    try {
      data = parseRetryBlock(source);
    } catch (error) {
      console.error(error);
      element.setText("This transcription retry block is invalid.");
      return;
    }
    element.addClass("flux-tts-retry");
    element.createDiv({ cls: "flux-tts-retry-error", text: data.message });
    const button = element.createEl("button", { text: "Retry transcription", cls: "mod-cta" });
    button.addEventListener("click", () => {
      button.disabled = true;
      button.setText("Retrying\u2026");
      void this.retryTranscription(notePath, source, data).catch((error) => {
        console.error(error);
        button.disabled = false;
        button.setText("Retry transcription");
        new import_obsidian7.Notice(`Retry failed: ${getErrorMessage(error)}`);
      });
    });
  }
  async retryTranscription(notePath, blockSource, data) {
    const note = this.app.vault.getAbstractFileByPath(notePath);
    const audio = this.app.vault.getAbstractFileByPath(data.audioPath);
    if (!(note instanceof import_obsidian7.TFile) || !(audio instanceof import_obsidian7.TFile)) {
      throw new Error("The recording note or audio file is missing.");
    }
    const apiKey = this.getApiKey();
    if (!apiKey) throw new Error("Add your Groq API key in Flux TTS settings first.");
    const buffer = await this.app.vault.readBinary(audio);
    const blob = new Blob([buffer], { type: mimeFromFileName(data.fileName) });
    const result = await transcribeAudio({
      apiKey,
      model: this.settings.model,
      blob,
      fileName: data.fileName,
      wantSegments: this.settings.segmentedTranscript
    });
    let transcript = this.settings.segmentedTranscript && result.segments.length ? renderSegmentedTranscript(result.segments, data.audioPath) : result.text.trim();
    if (this.settings.cleanupTranscript && !this.settings.segmentedTranscript && transcript) {
      transcript = await cleanupTranscript(apiKey, transcript);
    }
    const content = await this.app.vault.read(note);
    const block = `\`\`\`flux-tts-retry
${blockSource}
\`\`\``;
    if (!content.includes(block)) throw new Error("The retry block has changed or was removed.");
    await this.app.vault.modify(note, content.replace(block, transcript));
    new import_obsidian7.Notice("Transcription completed.");
  }
  async readNoteTemplate(path) {
    const normalized = (0, import_obsidian7.normalizePath)(path);
    for (const candidate of [normalized, `${normalized}.md`]) {
      const file = this.app.vault.getAbstractFileByPath(candidate);
      if (file instanceof import_obsidian7.TFile) {
        return this.app.vault.cachedRead(file);
      }
    }
    return null;
  }
  updateRibbonState(isRecording, overrideLabel, overrideIcon) {
    var _a, _b;
    if (isRecording) {
      (_a = this.waveform) == null ? void 0 : _a.start();
    } else {
      (_b = this.waveform) == null ? void 0 : _b.stop();
    }
    if (!this.ribbonIconEl) {
      return;
    }
    const label = overrideLabel != null ? overrideLabel : isRecording ? "Stop transcription" : "Start transcription";
    this.ribbonIconEl.toggleClass("is-active", isRecording);
    this.ribbonIconEl.setAttr("aria-label", label);
    this.ribbonIconEl.setAttr("aria-pressed", String(isRecording));
    (0, import_obsidian7.setIcon)(this.ribbonIconEl, overrideIcon != null ? overrideIcon : isRecording ? "square" : "mic");
    this.updateRibbonMenuLabel(label);
  }
  /**
   * The desktop `aria-label` above is enough on desktop, but Obsidian mobile
   * rebuilds its slide-up ribbon menu from each item's internal `title` — which
   * the DOM mutation never touches, so the menu kept showing "Start
   * transcription" after recording began. Update that title too so the next
   * menu rebuild reflects the real state. Internal API, guarded defensively so
   * it degrades to the desktop-only behavior if the shape ever changes.
   */
  updateRibbonMenuLabel(label) {
    var _a;
    const leftRibbon = this.app.workspace.leftRibbon;
    const item = (_a = leftRibbon == null ? void 0 : leftRibbon.items) == null ? void 0 : _a.find((entry) => entry.buttonEl === this.ribbonIconEl);
    if (item) {
      item.title = label;
      if (typeof item.ariaLabel === "string") {
        item.ariaLabel = label;
      }
    }
  }
  getApiKey() {
    const secretStorage = this.app.secretStorage;
    if (!secretStorage) {
      return "";
    }
    return secretStorage.getSecret(SECRET_KEY) || "";
  }
  setApiKey(value) {
    const secretStorage = this.app.secretStorage;
    if (!secretStorage) {
      throw new Error("Obsidian secret storage is not available.");
    }
    secretStorage.setSecret(SECRET_KEY, value.trim());
  }
};
