/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See https://github.com/smbp/flux-tts for the source code.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FluxTtsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/templates.ts
var import_obsidian = require("obsidian");
var FILENAME_TEMPLATE_KEYS = [
  "year",
  "month",
  "day",
  "hour",
  "minute",
  "second",
  "date",
  "time",
  "datetime"
];
var NOTE_TEMPLATE_KEYS = [
  ...FILENAME_TEMPLATE_KEYS,
  "transcript",
  "audioPath",
  "audioEmbed",
  "originalTranscript"
];
function createTemplateContext(date) {
  const pad = (value) => String(value).padStart(2, "0");
  const year = String(date.getFullYear());
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hour = pad(date.getHours());
  const minute = pad(date.getMinutes());
  const second = pad(date.getSeconds());
  const dateValue = `${year}-${month}-${day}`;
  const timeValue = `${hour}-${minute}-${second}`;
  return {
    year,
    month,
    day,
    hour,
    minute,
    second,
    date: dateValue,
    time: timeValue,
    datetime: `${dateValue} ${timeValue}`
  };
}
function renderTemplate(template, values) {
  return String(template).replace(/\{\{(.*?)\}\}/g, (_match, key) => {
    var _a;
    const normalizedKey = String(key).trim();
    return (_a = values[normalizedKey]) != null ? _a : "";
  });
}
function validateTemplate(template, allowedKeys) {
  const unknownKeys = [];
  const withoutPlaceholders = String(template).replace(/\{\{(.*?)\}\}/g, (_match, key) => {
    const normalizedKey = String(key).trim();
    if (!allowedKeys.includes(normalizedKey)) {
      unknownKeys.push(normalizedKey);
    }
    return "";
  });
  if (withoutPlaceholders.includes("{") || withoutPlaceholders.includes("}")) {
    return { valid: false, error: "Unbalanced braces \u2014 every placeholder needs matching {{ and }}." };
  }
  if (unknownKeys.length) {
    const listed = unknownKeys.map((key) => `{{${key}}}`).join(", ");
    return { valid: false, error: `Unknown placeholder: ${listed}` };
  }
  return { valid: true };
}
function sanitizeFileName(fileName) {
  const cleaned = String(fileName).replace(/[\\/:*?"<>|#^[\]{}]/g, "-").replace(/\s+/g, " ").trim();
  return cleaned || "Recording";
}
function sanitizeFolderPath(folderPath) {
  return (0, import_obsidian.normalizePath)(
    String(folderPath || "").split("/").map((part) => sanitizeFileName(part)).filter(Boolean).join("/")
  );
}

// src/settings.ts
var GROQ_MODELS = [
  { id: "whisper-large-v3-turbo", name: "Whisper Large v3 Turbo (fast)" },
  { id: "whisper-large-v3", name: "Whisper Large v3 (accurate)" }
];
var DEFAULT_SETTINGS = {
  model: "whisper-large-v3-turbo",
  saveLocation: "audio-folder",
  audioFolder: "audio recordings",
  noteFolderMode: "root",
  noteFolder: "",
  audioNameTemplate: "{{date}} {{time}}",
  noteNameTemplate: "Transcription_{{date}} {{time}}",
  useTemplate: false,
  noteTemplatePath: "",
  startDelayMs: 0,
  cleanupTranscript: false,
  segmentedTranscript: false
};
var API_KEY_MASK = "\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022";
var FluxTtsSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const hasApiKey = Boolean(this.plugin.getApiKey());
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Groq API key").setDesc(hasApiKey ? "A key is saved in Obsidian secret storage." : "Stored in Obsidian secret storage.").addText((text) => {
      text.setPlaceholder("gsk_...").setValue(hasApiKey ? API_KEY_MASK : "");
      text.inputEl.type = "password";
      text.inputEl.addEventListener("focus", () => {
        if (text.getValue() === API_KEY_MASK) {
          text.setValue("");
        }
      });
      text.inputEl.addEventListener("blur", () => {
        if (!text.getValue().trim() && this.plugin.getApiKey()) {
          text.setValue(API_KEY_MASK);
        }
      });
      text.onChange((value) => {
        const trimmed = value.trim();
        if (!trimmed || trimmed === API_KEY_MASK) {
          return;
        }
        this.plugin.setApiKey(trimmed);
      });
    }).addButton((button) => {
      button.setButtonText("Clear").setDisabled(!hasApiKey).onClick(() => {
        this.plugin.setApiKey("");
        this.display();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Groq model").setDesc("Turbo is the default for fastest transcription.").addDropdown((dropdown) => {
      GROQ_MODELS.forEach((model) => dropdown.addOption(model.id, model.name));
      dropdown.setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Recording").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Recording start delay").setDesc(
      "Milliseconds to wait after the microphone opens before capture begins. Raise this if the first second of your recordings gets clipped on slower hardware."
    ).addSlider((slider) => {
      slider.setLimits(0, 2e3, 100).setValue(this.plugin.settings.startDelayMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.startDelayMs = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Audio files").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Audio save location").setDesc("Choose where recorded audio files are written.").addDropdown((dropdown) => {
      dropdown.addOption("audio-folder", "Separate audio folder").addOption("attachments", "Obsidian attachments folder").addOption("root", "Vault root").setValue(this.plugin.settings.saveLocation).onChange(async (value) => {
        this.plugin.settings.saveLocation = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.saveLocation === "audio-folder") {
      new import_obsidian2.Setting(containerEl).setName("Audio folder").setDesc("Used when save location is set to a separate audio folder.").addText((text) => {
        text.setValue(this.plugin.settings.audioFolder).onChange(async (value) => {
          this.plugin.settings.audioFolder = value;
          await this.plugin.saveSettings();
        });
      });
    }
    this.addFilenameTemplateSetting({
      name: "Audio filename",
      desc: "Use {{date}}, {{time}}, {{datetime}}, {{year}}, {{month}}, {{day}}, {{hour}}, {{minute}}, and {{second}}.",
      exampleExtension: ".m4a",
      fallback: DEFAULT_SETTINGS.audioNameTemplate,
      getValue: () => this.plugin.settings.audioNameTemplate,
      setValue: (value) => {
        this.plugin.settings.audioNameTemplate = value;
      }
    });
    new import_obsidian2.Setting(containerEl).setName("Transcription notes").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Note save location").setDesc("Choose where transcription notes are created.").addDropdown((dropdown) => {
      dropdown.addOption("root", "Vault root").addOption("attachments", "Obsidian attachments folder").addOption("custom", "Separate folder").setValue(this.plugin.settings.noteFolderMode).onChange(async (value) => {
        this.plugin.settings.noteFolderMode = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.noteFolderMode === "custom") {
      new import_obsidian2.Setting(containerEl).setName("Note folder").setDesc("Used when note save location is set to a separate folder.").addText((text) => {
        text.setPlaceholder("transcriptions").setValue(this.plugin.settings.noteFolder).onChange(async (value) => {
          this.plugin.settings.noteFolder = value;
          await this.plugin.saveSettings();
        });
      });
    }
    this.addFilenameTemplateSetting({
      name: "Transcription note filename",
      desc: "Uses the same filename placeholders as audio files.",
      exampleExtension: ".md",
      fallback: DEFAULT_SETTINGS.noteNameTemplate,
      getValue: () => this.plugin.settings.noteNameTemplate,
      setValue: (value) => {
        this.plugin.settings.noteNameTemplate = value;
      }
    });
    new import_obsidian2.Setting(containerEl).setName("Use note template").setDesc("When off, notes contain only transcript text and the embedded audio link.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.useTemplate).onChange(async (value) => {
        this.plugin.settings.useTemplate = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    if (this.plugin.settings.useTemplate) {
      new import_obsidian2.Setting(containerEl).setName("Note template file").setDesc(
        "Vault path to a Markdown note used as the template, like Templates/Transcription.md. Supports {{transcript}}, {{audioPath}}, {{audioEmbed}}, {{originalTranscript}}, and the date and time placeholders."
      ).addText((text) => {
        text.setPlaceholder("Templates/Transcription.md").setValue(this.plugin.settings.noteTemplatePath).onChange(async (value) => {
          this.plugin.settings.noteTemplatePath = value.trim() ? (0, import_obsidian2.normalizePath)(value.trim()) : "";
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian2.Setting(containerEl).setName("Transcript processing").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Clean up transcript with AI").setDesc(
      'Send the raw transcript to a Groq language model to fix punctuation, remove filler words, and add paragraph breaks. The original transcript is kept too, under an "Original transcript" heading in the note. Skipped when timestamped segments are enabled, so segment text stays aligned with the audio.'
    ).addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.cleanupTranscript).onChange(async (value) => {
        this.plugin.settings.cleanupTranscript = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Timestamped segments").setDesc("Write the transcript as timestamped segments that link to their position in the audio file.").addToggle((toggle) => {
      toggle.setValue(this.plugin.settings.segmentedTranscript).onChange(async (value) => {
        this.plugin.settings.segmentedTranscript = value;
        await this.plugin.saveSettings();
      });
    });
  }
  addFilenameTemplateSetting(options) {
    const setting = new import_obsidian2.Setting(this.containerEl).setName(options.name).setDesc(options.desc);
    const previewEl = setting.descEl.createDiv({ cls: "flux-tts-template-preview" });
    const updatePreview = (template) => {
      var _a;
      const validation = validateTemplate(template, FILENAME_TEMPLATE_KEYS);
      if (!validation.valid) {
        previewEl.setText((_a = validation.error) != null ? _a : "Invalid template.");
        previewEl.addClass("flux-tts-template-invalid");
        return false;
      }
      const rendered = sanitizeFileName(renderTemplate(template, createTemplateContext(/* @__PURE__ */ new Date())));
      previewEl.setText(`Preview: ${rendered}${options.exampleExtension}`);
      previewEl.removeClass("flux-tts-template-invalid");
      return true;
    };
    setting.addText((text) => {
      text.setValue(options.getValue()).onChange(async (value) => {
        const template = value || options.fallback;
        if (!updatePreview(template)) {
          return;
        }
        options.setValue(template);
        await this.plugin.saveSettings();
      });
    });
    updatePreview(options.getValue());
  }
};

// src/recording.ts
var import_obsidian3 = require("obsidian");
var MIME_CANDIDATES = [
  { mime: "audio/mp4", extension: "m4a" },
  { mime: "audio/aac", extension: "aac" },
  { mime: "audio/webm;codecs=opus", extension: "webm" },
  { mime: "audio/webm", extension: "webm" },
  { mime: "audio/ogg;codecs=opus", extension: "ogg" },
  { mime: "audio/ogg", extension: "ogg" }
];
var SILENCE_RMS_THRESHOLD = 0.01;
var SILENCE_WARNING_MS = 5e3;
var SILENCE_AUTO_STOP_MS = 6e4;
var SILENCE_POLL_MS = 250;
var RecorderController = class {
  constructor(handlers) {
    this.handlers = handlers;
    this.state = "idle";
    this.cancelRequested = false;
    this.mediaRecorder = null;
    this.mediaStream = null;
    this.chunks = [];
    this.selectedMime = null;
    this.startedAt = 0;
    this.stoppedAt = null;
    this.audioContext = null;
    this.analyser = null;
    this.silenceInterval = null;
    this.deviceChangeHandler = null;
    this.activeDeviceId = "";
    this.disconnectNotified = false;
  }
  get isActive() {
    return this.state !== "idle";
  }
  get isRecording() {
    return this.state === "recording";
  }
  async start(startDelayMs) {
    if (this.state !== "idle") {
      return;
    }
    this.state = "starting";
    this.cancelRequested = false;
    this.stoppedAt = null;
    this.disconnectNotified = false;
    try {
      this.selectedMime = pickMimeType();
      this.mediaStream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const options = this.selectedMime ? { mimeType: this.selectedMime.mime } : void 0;
      const recorder = new MediaRecorder(this.mediaStream, options);
      this.mediaRecorder = recorder;
      this.chunks = [];
      recorder.ondataavailable = (event) => {
        if (event.data && event.data.size > 0) {
          this.chunks.push(event.data);
        }
      };
      recorder.onstop = () => this.finalize();
      if (startDelayMs > 0) {
        await sleep(startDelayMs);
      }
      if (this.cancelRequested) {
        this.cleanup();
        this.state = "idle";
        return;
      }
      recorder.start();
      this.startedAt = Date.now();
      this.state = "recording";
      this.watchSilence();
      this.watchDeviceChanges();
      this.handlers.onStateChange(true);
    } catch (error) {
      this.cleanup();
      this.state = "idle";
      this.handlers.onStateChange(false);
      throw error instanceof Error ? error : new Error(String(error));
    }
  }
  stop() {
    if (this.state === "starting") {
      this.cancelRequested = true;
      return;
    }
    if (this.state !== "recording" || !this.mediaRecorder || this.mediaRecorder.state !== "recording") {
      return;
    }
    this.stoppedAt = Date.now();
    this.handlers.onStateChange(false);
    this.mediaRecorder.stop();
  }
  /** Tear everything down without producing a recording (plugin unload). */
  dispose() {
    this.cancelRequested = true;
    if (this.mediaRecorder) {
      this.mediaRecorder.onstop = null;
      if (this.mediaRecorder.state === "recording") {
        try {
          this.mediaRecorder.stop();
        } catch (error) {
          console.error(error);
        }
      }
    }
    this.cleanup();
    this.state = "idle";
  }
  finalize() {
    var _a, _b;
    const chunks = this.chunks;
    const selectedMime = this.selectedMime;
    const mimeType = (selectedMime == null ? void 0 : selectedMime.mime) || ((_a = chunks[0]) == null ? void 0 : _a.type) || "audio/webm";
    const extension = (selectedMime == null ? void 0 : selectedMime.extension) || extensionFromMime(mimeType);
    const durationSeconds = Math.max(0, (((_b = this.stoppedAt) != null ? _b : Date.now()) - this.startedAt) / 1e3);
    this.cleanup();
    this.state = "idle";
    if (!chunks.length) {
      this.handlers.onError(new Error("No audio was captured."));
      return;
    }
    this.handlers.onFinish({
      blob: new Blob(chunks, { type: mimeType }),
      mimeType,
      extension,
      durationSeconds
    });
  }
  cleanup() {
    var _a;
    this.stopSilenceWatch();
    if (this.deviceChangeHandler && ((_a = navigator.mediaDevices) == null ? void 0 : _a.removeEventListener)) {
      navigator.mediaDevices.removeEventListener("devicechange", this.deviceChangeHandler);
      this.deviceChangeHandler = null;
    }
    if (this.mediaStream) {
      this.mediaStream.getTracks().forEach((track) => track.stop());
      this.mediaStream = null;
    }
    this.mediaRecorder = null;
    this.chunks = [];
    this.selectedMime = null;
  }
  watchSilence() {
    if (typeof AudioContext === "undefined" || !this.mediaStream) {
      return;
    }
    let analyser;
    try {
      this.audioContext = new AudioContext();
      const source = this.audioContext.createMediaStreamSource(this.mediaStream);
      analyser = this.audioContext.createAnalyser();
      analyser.fftSize = 2048;
      source.connect(analyser);
      this.analyser = analyser;
      if (this.audioContext.state === "suspended") {
        void this.audioContext.resume();
      }
    } catch (error) {
      console.error(error);
      return;
    }
    const data = new Uint8Array(analyser.fftSize);
    let hasHeardSound = false;
    let silenceStartedAt = Date.now();
    let earlyWarningShown = false;
    this.silenceInterval = window.setInterval(() => {
      var _a;
      if (((_a = this.audioContext) == null ? void 0 : _a.state) !== "running") {
        return;
      }
      analyser.getByteTimeDomainData(data);
      let sum = 0;
      for (let index = 0; index < data.length; index += 1) {
        const value = (data[index] - 128) / 128;
        sum += value * value;
      }
      const rms = Math.sqrt(sum / data.length);
      if (rms > SILENCE_RMS_THRESHOLD) {
        hasHeardSound = true;
        silenceStartedAt = null;
        return;
      }
      if (silenceStartedAt === null) {
        silenceStartedAt = Date.now();
      }
      const silenceElapsed = Date.now() - silenceStartedAt;
      if (!hasHeardSound && !earlyWarningShown && silenceElapsed >= SILENCE_WARNING_MS) {
        earlyWarningShown = true;
        new import_obsidian3.Notice("No audio detected from your microphone. Check your input device.");
      }
      if (silenceElapsed >= SILENCE_AUTO_STOP_MS) {
        this.stopSilenceWatch();
        new import_obsidian3.Notice("No audio detected for over a minute \u2014 stopping the recording automatically to save battery.");
        this.stop();
      }
    }, SILENCE_POLL_MS);
  }
  stopSilenceWatch() {
    if (this.silenceInterval !== null) {
      window.clearInterval(this.silenceInterval);
      this.silenceInterval = null;
    }
    if (this.audioContext) {
      this.audioContext.close().catch(() => {
      });
      this.audioContext = null;
    }
    this.analyser = null;
  }
  watchDeviceChanges() {
    var _a, _b, _c, _d;
    if (!((_a = navigator.mediaDevices) == null ? void 0 : _a.addEventListener)) {
      return;
    }
    const track = (_b = this.mediaStream) == null ? void 0 : _b.getAudioTracks()[0];
    this.activeDeviceId = (_d = (_c = track == null ? void 0 : track.getSettings) == null ? void 0 : _c.call(track).deviceId) != null ? _d : "";
    this.deviceChangeHandler = () => {
      void this.checkInputStillPresent();
    };
    navigator.mediaDevices.addEventListener("devicechange", this.deviceChangeHandler);
  }
  async checkInputStillPresent() {
    if (this.state !== "recording" || this.disconnectNotified) {
      return;
    }
    let devices;
    try {
      devices = await navigator.mediaDevices.enumerateDevices();
    } catch (error) {
      console.error(error);
      return;
    }
    const inputs = devices.filter((device) => device.kind === "audioinput");
    const stillPresent = this.activeDeviceId ? inputs.some((device) => device.deviceId === this.activeDeviceId) : inputs.length > 0;
    if (stillPresent) {
      return;
    }
    this.disconnectNotified = true;
    const fragment = document.createDocumentFragment();
    fragment.createSpan({
      text: "Your recording input disconnected \u2014 audio after this point may be silent. "
    });
    const button = fragment.createEl("button", { text: "Stop now" });
    const notice = new import_obsidian3.Notice(fragment, 0);
    button.addEventListener("click", () => {
      notice.hide();
      this.stop();
    });
  }
};
function pickMimeType() {
  for (const candidate of MIME_CANDIDATES) {
    if (MediaRecorder.isTypeSupported(candidate.mime)) {
      return candidate;
    }
  }
  return null;
}
function extensionFromMime(mimeType) {
  if (mimeType.includes("mp4")) return "m4a";
  if (mimeType.includes("aac")) return "aac";
  if (mimeType.includes("ogg")) return "ogg";
  if (mimeType.includes("webm")) return "webm";
  return "audio";
}
function sleep(ms) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}

// src/transcription.ts
var import_obsidian4 = require("obsidian");
var GROQ_TRANSCRIPTION_URL = "https://api.groq.com/openai/v1/audio/transcriptions";
var GROQ_CHAT_URL = "https://api.groq.com/openai/v1/chat/completions";
var CLEANUP_MODEL = "llama-3.3-70b-versatile";
var CLEANUP_SYSTEM_PROMPT = "You clean up raw speech-to-text transcripts. Fix punctuation and capitalization, remove filler words (um, uh, you know, like when used as filler), and break the text into readable paragraphs. Do not summarize, rephrase, add, or remove any substantive content. Return only the cleaned transcript with no preamble or commentary.";
var SPEECH_WORDS_PER_MINUTE = 150;
var LENGTH_CHECK_MIN_SECONDS = 15;
var LENGTH_CHECK_MIN_RATIO = 0.3;
async function transcribeAudio(options) {
  var _a, _b;
  const boundary = `----flux-tts-${Date.now().toString(36)}`;
  const body = await buildMultipartBody(boundary, [
    { name: "model", value: options.model },
    { name: "response_format", value: options.wantSegments ? "verbose_json" : "text" },
    {
      name: "file",
      fileName: options.fileName,
      contentType: options.blob.type || "application/octet-stream",
      value: await options.blob.arrayBuffer()
    }
  ]);
  const response = await (0, import_obsidian4.requestUrl)({
    url: GROQ_TRANSCRIPTION_URL,
    method: "POST",
    contentType: `multipart/form-data; boundary=${boundary}`,
    headers: {
      Authorization: `Bearer ${options.apiKey}`
    },
    body,
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Groq returned HTTP ${response.status}: ${response.text}`);
  }
  if (!options.wantSegments) {
    return { text: response.text, segments: [] };
  }
  const parsed = JSON.parse(response.text);
  return {
    text: String((_a = parsed.text) != null ? _a : ""),
    segments: ((_b = parsed.segments) != null ? _b : []).map((segment) => {
      var _a2;
      return {
        start: Number(segment.start) || 0,
        end: Number(segment.end) || 0,
        text: String((_a2 = segment.text) != null ? _a2 : "")
      };
    })
  };
}
async function cleanupTranscript(apiKey, transcript) {
  var _a, _b, _c;
  const response = await (0, import_obsidian4.requestUrl)({
    url: GROQ_CHAT_URL,
    method: "POST",
    contentType: "application/json",
    headers: {
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: CLEANUP_MODEL,
      temperature: 0.2,
      messages: [
        { role: "system", content: CLEANUP_SYSTEM_PROMPT },
        { role: "user", content: transcript }
      ]
    }),
    throw: false
  });
  if (response.status < 200 || response.status >= 300) {
    throw new Error(`Groq returned HTTP ${response.status}: ${response.text}`);
  }
  const parsed = response.json;
  const content = (_c = (_b = (_a = parsed == null ? void 0 : parsed.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content;
  if (typeof content !== "string" || !content.trim()) {
    throw new Error("Transcript cleanup returned no content.");
  }
  return content.trim();
}
function renderSegmentedTranscript(segments, audioPath) {
  return segments.map((segment) => {
    const seconds = Math.max(0, Math.floor(segment.start));
    const label = formatTimestamp(segment.start);
    return `[[${audioPath}#t=${seconds}|${label}]] ${segment.text.trim()}`;
  }).join("\n\n");
}
function transcriptLengthWarning(transcript, durationSeconds) {
  if (durationSeconds < LENGTH_CHECK_MIN_SECONDS) {
    return null;
  }
  const wordCount = transcript.split(/\s+/).filter(Boolean).length;
  const expectedSeconds = wordCount / SPEECH_WORDS_PER_MINUTE * 60;
  if (expectedSeconds >= durationSeconds * LENGTH_CHECK_MIN_RATIO) {
    return null;
  }
  const duration = formatTimestamp(durationSeconds);
  return `

> [!warning] This transcript seems short for a ${duration} recording \u2014 worth checking the audio.`;
}
function formatTimestamp(totalSeconds) {
  const whole = Math.max(0, Math.floor(totalSeconds));
  const hours = Math.floor(whole / 3600);
  const minutes = Math.floor(whole % 3600 / 60);
  const seconds = whole % 60;
  const pad = (value) => String(value).padStart(2, "0");
  return hours > 0 ? `${hours}:${pad(minutes)}:${pad(seconds)}` : `${minutes}:${pad(seconds)}`;
}
async function buildMultipartBody(boundary, parts) {
  const encoder = new TextEncoder();
  const buffers = [];
  for (const part of parts) {
    let header = `--${boundary}\r
Content-Disposition: form-data; name="${part.name}"`;
    if (part.fileName) {
      header += `; filename="${part.fileName}"`;
    }
    header += "\r\n";
    if (part.contentType) {
      header += `Content-Type: ${part.contentType}\r
`;
    }
    header += "\r\n";
    buffers.push(encoder.encode(header).buffer);
    buffers.push(
      part.value instanceof ArrayBuffer ? part.value : encoder.encode(String(part.value)).buffer
    );
    buffers.push(encoder.encode("\r\n").buffer);
  }
  buffers.push(encoder.encode(`--${boundary}--\r
`).buffer);
  return concatArrayBuffers(buffers);
}
function concatArrayBuffers(buffers) {
  const totalLength = buffers.reduce((total, buffer) => total + buffer.byteLength, 0);
  const output = new Uint8Array(totalLength);
  let offset = 0;
  for (const buffer of buffers) {
    output.set(new Uint8Array(buffer), offset);
    offset += buffer.byteLength;
  }
  return output.buffer;
}

// src/paths.ts
var import_obsidian5 = require("obsidian");
function getAttachmentFolder(app) {
  var _a, _b;
  const configured = (_b = (_a = app.vault).getConfig) == null ? void 0 : _b.call(
    _a,
    "attachmentFolderPath"
  );
  if (typeof configured === "string" && configured.trim()) {
    return sanitizeFolderPath(configured);
  }
  return "";
}
function resolveAudioPath(app, settings, fileName) {
  const cleanFileName = sanitizeFileName(fileName);
  if (settings.saveLocation === "root") {
    return cleanFileName;
  }
  if (settings.saveLocation === "attachments") {
    const attachmentFolder = getAttachmentFolder(app);
    if (attachmentFolder) {
      return (0, import_obsidian5.normalizePath)(`${attachmentFolder}/${cleanFileName}`);
    }
    new import_obsidian5.Notice("No Obsidian attachment folder is configured; saving audio at vault root.");
    return cleanFileName;
  }
  const folder = sanitizeFolderPath(settings.audioFolder) || DEFAULT_SETTINGS.audioFolder;
  return (0, import_obsidian5.normalizePath)(`${folder}/${cleanFileName}`);
}
function resolveNotePath(app, settings, fileName) {
  const cleanFileName = sanitizeFileName(fileName);
  if (settings.noteFolderMode === "attachments") {
    const attachmentFolder = getAttachmentFolder(app);
    if (attachmentFolder) {
      return (0, import_obsidian5.normalizePath)(`${attachmentFolder}/${cleanFileName}`);
    }
    new import_obsidian5.Notice("No Obsidian attachment folder is configured; creating the note at vault root.");
    return cleanFileName;
  }
  if (settings.noteFolderMode === "custom") {
    const folder = sanitizeFolderPath(settings.noteFolder);
    if (folder) {
      return (0, import_obsidian5.normalizePath)(`${folder}/${cleanFileName}`);
    }
  }
  return cleanFileName;
}
async function ensureParentFolder(app, path) {
  const folder = path.includes("/") ? path.slice(0, path.lastIndexOf("/")) : "";
  if (folder) {
    await ensureFolder(app, folder);
  }
}
async function ensureFolder(app, path) {
  const normalized = (0, import_obsidian5.normalizePath)(path);
  if (!normalized || app.vault.getAbstractFileByPath(normalized)) {
    return;
  }
  const parts = normalized.split("/");
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(current)) {
      await app.vault.createFolder(current);
    }
  }
}
async function uniquePath(app, path, extension) {
  const normalized = (0, import_obsidian5.normalizePath)(path);
  if (!app.vault.getAbstractFileByPath(normalized)) {
    return normalized;
  }
  const base = extension && normalized.toLowerCase().endsWith(extension.toLowerCase()) ? normalized.slice(0, -extension.length) : normalized;
  const suffix = extension && normalized.toLowerCase().endsWith(extension.toLowerCase()) ? extension : "";
  for (let index = 2; index < 1e3; index += 1) {
    const candidate = `${base} ${index}${suffix}`;
    if (!app.vault.getAbstractFileByPath(candidate)) {
      return candidate;
    }
  }
  throw new Error(`Could not find an available filename for ${normalized}`);
}
async function writeBinaryUnique(app, path, extension, buffer) {
  await ensureParentFolder(app, path);
  const target = await uniquePath(app, path, extension);
  await app.vault.createBinary(target, buffer);
  return target;
}
async function createNoteUnique(app, path, content) {
  await ensureParentFolder(app, path);
  const target = await uniquePath(app, path, ".md");
  await app.vault.create(target, content);
  return target;
}

// src/main.ts
var PLUGIN_ID = "flux-tts";
var SECRET_KEY = `${PLUGIN_ID}-groq-api-key`;
var FluxTtsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.recorder = null;
    this.ribbonIconEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.recorder = new RecorderController({
      onFinish: (result) => {
        this.handleRecordingFinished(result).catch((error) => {
          console.error(error);
          new import_obsidian6.Notice(`Recording failed: ${error.message || error}`);
        });
      },
      onError: (error) => {
        console.error(error);
        new import_obsidian6.Notice(error.message);
      },
      onStateChange: (isRecording) => this.updateRibbonState(isRecording)
    });
    this.ribbonIconEl = this.addRibbonIcon("mic", "Start transcription", () => {
      void this.toggleRecording();
    });
    this.addCommand({
      id: "toggle-recording",
      name: "Toggle recording",
      callback: () => void this.toggleRecording()
    });
    this.addCommand({
      id: "start-recording",
      name: "Start recording",
      callback: () => {
        var _a;
        if ((_a = this.recorder) == null ? void 0 : _a.isActive) {
          new import_obsidian6.Notice("Already recording.");
          return;
        }
        void this.startRecording();
      }
    });
    this.addCommand({
      id: "stop-recording",
      name: "Stop recording",
      callback: () => {
        var _a;
        if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) {
          new import_obsidian6.Notice("Not recording.");
          return;
        }
        this.stopRecording();
      }
    });
    this.addCommand({
      id: "cycle-transcription-model",
      name: "Cycle transcription model",
      callback: async () => {
        const index = GROQ_MODELS.findIndex((model) => model.id === this.settings.model);
        const next = GROQ_MODELS[(index + 1) % GROQ_MODELS.length];
        this.settings.model = next.id;
        await this.saveSettings();
        new import_obsidian6.Notice(`Transcription model: ${next.name}`);
      }
    });
    this.addSettingTab(new FluxTtsSettingTab(this.app, this));
    this.updateRibbonState(false);
  }
  onunload() {
    var _a;
    (_a = this.recorder) == null ? void 0 : _a.dispose();
    this.recorder = null;
  }
  async loadSettings() {
    var _a;
    const saved = (_a = await this.loadData()) != null ? _a : {};
    if (!saved.noteFolderMode) {
      saved.noteFolderMode = typeof saved.noteFolder === "string" && saved.noteFolder.trim() ? "custom" : "root";
    }
    delete saved.noteTemplate;
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
    this.validateSettings();
  }
  async saveSettings() {
    this.validateSettings();
    await this.saveData(this.settings);
  }
  validateSettings() {
    if (!GROQ_MODELS.some((model) => model.id === this.settings.model)) {
      this.settings.model = DEFAULT_SETTINGS.model;
    }
    if (!["audio-folder", "attachments", "root"].includes(this.settings.saveLocation)) {
      this.settings.saveLocation = DEFAULT_SETTINGS.saveLocation;
    }
    if (!["root", "attachments", "custom"].includes(this.settings.noteFolderMode)) {
      this.settings.noteFolderMode = DEFAULT_SETTINGS.noteFolderMode;
    }
    const stringKeys = ["audioFolder", "noteFolder", "audioNameTemplate", "noteNameTemplate", "noteTemplatePath"];
    for (const key of stringKeys) {
      if (typeof this.settings[key] !== "string") {
        this.settings[key] = DEFAULT_SETTINGS[key];
      }
    }
    for (const key of ["audioNameTemplate", "noteNameTemplate"]) {
      if (!validateTemplate(this.settings[key], FILENAME_TEMPLATE_KEYS).valid) {
        this.settings[key] = DEFAULT_SETTINGS[key];
      }
    }
    const delay = Number(this.settings.startDelayMs);
    this.settings.startDelayMs = Number.isFinite(delay) ? Math.min(2e3, Math.max(0, Math.round(delay))) : 0;
    this.settings.useTemplate = Boolean(this.settings.useTemplate);
    this.settings.cleanupTranscript = Boolean(this.settings.cleanupTranscript);
    this.settings.segmentedTranscript = Boolean(this.settings.segmentedTranscript);
  }
  async toggleRecording() {
    var _a;
    if ((_a = this.recorder) == null ? void 0 : _a.isActive) {
      this.stopRecording();
      return;
    }
    await this.startRecording();
  }
  async startRecording() {
    var _a;
    if (!this.recorder || this.recorder.isActive) {
      return;
    }
    if (!((_a = navigator.mediaDevices) == null ? void 0 : _a.getUserMedia) || typeof MediaRecorder === "undefined") {
      new import_obsidian6.Notice("Audio recording is not available in this Obsidian environment.");
      return;
    }
    if (!this.getApiKey()) {
      new import_obsidian6.Notice("Add your Groq API key in Flux TTS settings first.");
      return;
    }
    try {
      await this.recorder.start(this.settings.startDelayMs);
      if (this.recorder.isRecording) {
        new import_obsidian6.Notice("Recording started.");
      }
    } catch (error) {
      console.error(error);
      new import_obsidian6.Notice(`Could not start recording: ${error.message || error}`);
    }
  }
  stopRecording() {
    var _a;
    if (!((_a = this.recorder) == null ? void 0 : _a.isActive)) {
      return;
    }
    const wasRecording = this.recorder.isRecording;
    this.recorder.stop();
    if (wasRecording) {
      new import_obsidian6.Notice("Saving and transcribing...");
    }
  }
  async handleRecordingFinished(result) {
    const context = createTemplateContext(/* @__PURE__ */ new Date());
    const audioFileName = `${renderTemplate(this.settings.audioNameTemplate, context)}.${result.extension}`;
    const noteFileName = `${renderTemplate(this.settings.noteNameTemplate, context)}.md`;
    const audioPath = resolveAudioPath(this.app, this.settings, audioFileName);
    const notePath = resolveNotePath(this.app, this.settings, noteFileName);
    const audioBuffer = await result.blob.arrayBuffer();
    const savedAudioPath = await writeBinaryUnique(this.app, audioPath, `.${result.extension}`, audioBuffer);
    let rawTranscript = "";
    let segments = [];
    let transcriptionFailed = false;
    const apiKey = this.getApiKey();
    try {
      if (!apiKey) {
        throw new Error("Missing Groq API key.");
      }
      const transcription = await transcribeAudio({
        apiKey,
        model: this.settings.model,
        blob: result.blob,
        fileName: audioFileName,
        wantSegments: this.settings.segmentedTranscript
      });
      rawTranscript = transcription.text.trim();
      segments = transcription.segments;
    } catch (error) {
      console.error(error);
      transcriptionFailed = true;
      rawTranscript = `Transcription failed: ${error.message || error}`;
      new import_obsidian6.Notice("Audio saved, but transcription failed.");
    }
    const useSegments = !transcriptionFailed && this.settings.segmentedTranscript && segments.length > 0;
    let displayTranscript = rawTranscript;
    let originalTranscript = "";
    if (!transcriptionFailed && this.settings.cleanupTranscript && !useSegments && rawTranscript) {
      try {
        displayTranscript = await cleanupTranscript(apiKey, rawTranscript);
        originalTranscript = rawTranscript;
      } catch (error) {
        console.error(error);
        new import_obsidian6.Notice("Transcript cleanup failed; using the raw transcript.");
      }
    }
    const transcriptForNote = useSegments ? renderSegmentedTranscript(segments, savedAudioPath) : displayTranscript;
    let noteBody = await this.renderNote(transcriptForNote, savedAudioPath, context, originalTranscript);
    if (!transcriptionFailed) {
      const warning = transcriptLengthWarning(rawTranscript, result.durationSeconds);
      if (warning) {
        noteBody += warning;
      }
    }
    const createdNotePath = await createNoteUnique(this.app, notePath, noteBody);
    const file = this.app.vault.getAbstractFileByPath(createdNotePath);
    if (file instanceof import_obsidian6.TFile) {
      await this.app.workspace.getLeaf(false).openFile(file);
    }
    new import_obsidian6.Notice("Transcription saved.");
  }
  async renderNote(transcript, audioPath, context, originalTranscript) {
    const values = Object.assign({}, context, {
      transcript: transcript.trim(),
      audioPath,
      audioEmbed: `![[${audioPath}]]`,
      originalTranscript: originalTranscript.trim()
    });
    if (this.settings.useTemplate && this.settings.noteTemplatePath) {
      const template = await this.readNoteTemplate(this.settings.noteTemplatePath);
      if (template !== null) {
        return renderTemplate(template, values).trim();
      }
      new import_obsidian6.Notice(`Note template file not found: ${this.settings.noteTemplatePath}. Using the default layout.`);
    }
    let body = `${values.transcript}

${values.audioEmbed}`;
    if (values.originalTranscript) {
      body += `

## Original transcript

${values.originalTranscript}`;
    }
    return body;
  }
  async readNoteTemplate(path) {
    const normalized = (0, import_obsidian6.normalizePath)(path);
    for (const candidate of [normalized, `${normalized}.md`]) {
      const file = this.app.vault.getAbstractFileByPath(candidate);
      if (file instanceof import_obsidian6.TFile) {
        return this.app.vault.cachedRead(file);
      }
    }
    return null;
  }
  updateRibbonState(isRecording) {
    if (!this.ribbonIconEl) {
      return;
    }
    this.ribbonIconEl.toggleClass("is-active", isRecording);
    this.ribbonIconEl.setAttr("aria-label", isRecording ? "Stop transcription" : "Start transcription");
    this.ribbonIconEl.setAttr("aria-pressed", String(isRecording));
  }
  getApiKey() {
    const secretStorage = this.app.secretStorage;
    if (!secretStorage) {
      return "";
    }
    return secretStorage.getSecret(SECRET_KEY) || "";
  }
  setApiKey(value) {
    const secretStorage = this.app.secretStorage;
    if (!secretStorage) {
      throw new Error("Obsidian secret storage is not available.");
    }
    secretStorage.setSecret(SECRET_KEY, value.trim());
  }
};
